- src/main/resources/site/parts/keyFigure/keyFigure.es6
> MIMIR-323 undo hiding of keyFigures without values

- src/main/resources/site/filters/router.es6
fixed bug where 404 was always shown in edit mode
> MIMIR-311 don't show 404 while in edit mode

- build.gradle
- package-lock.json
- package.json
- src/main/resources/lib/ssb/cache.ts
- src/main/resources/main.js
- src/main/resources/site/filters/router.es6
> MIMIR-239 improve kommunefakta caching

- src/main/resources/site/processors/react4xpAssetSource.es6
- src/main/resources/site/site.xml
> MIMIR-427 fix react4xp asset src paths

- src/main/resources/assets/js/app/highchart.es6
- src/main/resources/lib/highcharts/config.es6
- src/main/resources/site/parts/highchart/highchart.es6
> MIMIR-480 highchart no number message

- package-lock.json
- src/main/resources/site/processors/react4xpAssetSource.es6
> MIMIR-427 handle react4xp assets for admin pages as well

- src/main/resources/site/parts/menuDropdown/menuDropdown.es6
- src/main/resources/site/parts/menuDropdown/menuDropdown.html
Glemte å fjerne duplikat fylkesnavn fra stickymenyen
> MIMIR-483: Removed county from municipalityname on stickyMenu

- src/main/resources/lib/ssb/menu.ts
- src/main/resources/react4xp/_entries/Header.jsx
- Check icon if it is published
> Fix bug where reactcomponent logs errors

- src/main/resources/assets/styles/_banner.scss
- src/main/resources/assets/styles/_layout.scss
- src/main/resources/assets/styles/main.scss
mimir-496 reduced the minimum height of grey area on small screens
mimir-437 removed negative margin from .row on small screens
mimir-498 reduced height of banner on small screens, also bumbed h1 font size
> multiple jira tickets

- src/main/resources/assets/styles/_header.scss
- src/main/resources/react4xp/_entries/Header.jsx
> Fixed styling active tabelement Header

- src/main/resources/lib/ssb/utils.es6
added support for edge case where thousand number would also have decimal
> Fixed HumanReadableFormat

- src/main/resources/assets/styles/_banner.scss
- src/main/resources/assets/styles/_highchart.scss
- src/main/resources/assets/styles/_layout.scss
- src/main/resources/assets/styles/main.scss
also fixed padding on layout on mobile
> fixed width of charts

- src/main/resources/assets/styles/_article.scss
- src/main/resources/site/macros/highchart/highchart-config.ts
- src/main/resources/site/macros/highchart/highchart.es6
- src/main/resources/site/macros/highchart/highchart.xml
- src/main/resources/site/parts/article/article.html
- src/main/resources/site/parts/divider/divider.es6
> MIMIR-387 highchart macro and some layout fixes in article

- package-lock.json
- package.json
- src/main/resources/assets/styles/_relatedContentBox.scss
- src/main/resources/site/parts/relatedFactPage/relatedFactPage.html
- src/main/resources/site/parts/relatedFactPage/relatedFactPage.jsx
also extended cards to 4 visible
And replaced orientation prop with the correct className prop
> Replaced ImageLink component

- src/main/resources/site/parts/infoGraphics/infoGraphics-part-config.ts
- src/main/resources/site/parts/infoGraphics/infoGraphics.es6
- src/main/resources/site/parts/infoGraphics/infoGraphics.xml
Changed altText to be retrieved from image meta data instead of part
textline
also changed label on part textline to show its not in use
> Changed altText from part to content

- src/main/resources/assets/js/app/autocomplete.es6
- src/main/resources/assets/styles/_menuDropdown.scss
also added border to show-map button on focus
> Set tab to skip to show-map button

- package-lock.json
- package.json
Since last build in drone failed, im trying a new version of ssb-component-library
> Update ssb-component-library to 2.0.16

- src/main/resources/assets/js/app/autocomplete.es6
- src/main/resources/assets/styles/_relatedContentBox.scss
- src/main/resources/site/parts/relatedFactPage/relatedFactPage.jsx
also added adjustment for mimir-490
> Added fix for kommunefakta main page

- src/main/resources/site/parts/menuDropdown/menuDropdown.html
> Added missing aria-label searchbutton responsive view

- package-lock.json
- src/main/resources/site/pages/default/default.html
MIMIR-535
Needs config to work - see PR in mimir-config repo for details
> Mimir 535 googleanalytics siteimprove

- build.gradle
- docs/Dataquery.md
- package-lock.json
- src/main/resources/main.es6
- Change main.js to main.es6 to support new js functions
- Change import in gradle
- Update doc
MIMIR-585
> Main.js failed on startup

- src/main/resources/site/macros/tableLink/tableLink.es6
> Fixed small error

- src/main/resources/site/parts/article/article.html
originaly fixed in mimir-332, but taken out in own branch
> Fixed if check

- src/main/resources/lib/highcharts/config.es6
added button list to remove 3 default buttons
> Added button list

- src/main/resources/site/content-types/article/article.ts
- src/main/resources/site/content-types/article/article.xml
- src/main/resources/site/parts/relatedFactPage/relatedFactPage.es6
Added single page selector instead
> Removed list selection

- src/main/resources/site/content-types/article/article.xml
changed maks itemSets from unlimited to 1
> Mimir 431 faktasider artikkel

- src/main/resources/site/filters/router.es6
> MIMIR-549 replace title on routed pages (kommunefakta)

- src/main/resources/site/parts/divider/divider.es6
- src/main/resources/site/parts/divider/divider.html
UD (W3-validator): Fixes the duplicate divider ids.
> MIMIR-592: divider id

- src/main/resources/assets/styles/main.scss
also margins to auto so it would be centered
> added width to xp-region

- src/main/resources/admin/tools/dashboard/dashboard.es6
- src/main/resources/lib/ssb/cache.ts
- src/main/resources/react4xp/_entries/Dashboard/ClearCacheButton.jsx
- src/main/resources/react4xp/_entries/Dashboard/Dashboard.jsx
- src/main/resources/services/clearCache/clearCache.es6
- src/main/resources/services/clearCache/clearCache.xml
> Mimir 597 empty cache button

- src/main/resources/admin/tools/dashboard/dashboard.es6
- src/main/resources/lib/repo/query.ts
- src/main/resources/lib/ssb/utils.es6
- src/main/resources/react4xp/_entries/Dashboard/DashboardDataQuery.jsx
- Change logical operator from or to and
- Add locale to moment
- Add linebreak
- Add check for 'first' property on "isPublished" check
> MIMIR-326: Debug and fix errors

- docs/Services.md
- src/main/resources/services/customSelectorMunicipals/customSelectorMunicipals.es6
- Update jsdoc in customSelectorMunicipality
MIMIR-448
> MIMIR-448 Update documentation on dashboard service

- src/main/resources/assets/js/app/map.es6
- src/main/resources/site/filters/router.es6
- fix municipality urls in map for kommuneareal
- lint map.es6
- bugfix with preview in content-studio for municipality pages
> Kommuneareal

- src/main/resources/site/content-types/omStatistikken/omStatistikken.ts
- src/main/resources/site/content-types/omStatistikken/omStatistikken.xml
Also added field-sets to the other fields
> MIMIR-471: Added Om sesongjustering

- src/main/resources/site/content-types/page/page.ts
- src/main/resources/site/content-types/page/page.xml
removed ingress and alt. title fields
> removed page input fields

- src/main/resources/lib/ssb/utils.es6
- src/main/resources/site/parts/banner/banner.es6
- src/main/resources/site/parts/menuBox/menuBox.es6
- src/main/resources/site/parts/profiledBox/profiledBox.es6
- src/main/resources/site/parts/relatedArticles/relatedArticles.es6
replaced getImageCaption with getImageAlt all places that add images
> Added getImageAlt function

- src/main/resources/admin/tools/dashboard/dashboard.xml
- src/main/resources/lib/dataquery.ts
- src/main/resources/lib/repo/common.ts
- src/main/resources/lib/repo/eventLog.ts
- src/main/resources/lib/repo/query.ts
- src/main/resources/lib/ssb/dataquery.es6
- src/main/resources/lib/task.ts
- src/main/resources/lib/tbml/tbml.ts
- src/main/resources/main.es6
- src/main/resources/services/dashboard/dashboard.es6
- Split array in x 'chunks' and create tasks to run them asynchronus
- Add logging for super user
Change name on dashboard
MIMIR-395
> Change data requests to be asynchronus

- package-lock.json
- src/main/resources/admin/tools/dashboard/dashboard.es6
- src/main/resources/assets/styles/_dashboard.scss
- src/main/resources/lib/repo/eventLog.ts
- src/main/resources/react4xp/_entries/Dashboard/DashboardDataQuery.jsx
- Add warning icon in dashboard for failed statuses
- Add `default` in url to contentstudio to quickfix new url shceme for 7.3
MIMIR-654
> MIMIR 654: warning icon in dashboard

- src/main/resources/admin/tools/dashboard/dashboard.es6
- src/main/resources/assets/styles/_dashboard.scss
- src/main/resources/react4xp/_entries/Dashboard/Dashboard.jsx
- src/main/resources/react4xp/_entries/Dashboard/DashboardDataQuery.jsx
- src/main/resources/react4xp/_entries/Dashboard/DataQueryTable.jsx
- `DataQueryTable` wrapper that adds sortable header to the existing dataquery table renderer `Dashboard::renderDataQueries`
> MIMIR-646 : dashboard sort columns

- src/main/resources/assets/styles/_dashboard.scss
- src/main/resources/lib/dataquery.ts
- src/main/resources/lib/repo/query.ts
- src/main/resources/lib/ssb/dataset/dataset.ts
- src/main/resources/lib/ssb/dataset/statbankApi.ts
- src/main/resources/lib/ssb/dataset/tbprocessor.ts
- src/main/resources/lib/tbml/tbml.ts
tbprocessor import now working
Still missing:
delete new dataset
cron-job
> Mimir 696 dataset from repo in dashboard

- src/main/resources/lib/highcharts/highcharts.es6
> MIMIR-720 Highchart error

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- use v1.0.1
- works only with gradle 6.5, so pulling it up too
> MIMIR-740 : Upgrade react4xp

- package-lock.json
- src/main/resources/main.es6
MIMIR-735
config pr: https://github.com/statisticsnorway/mimir-config/pull/6
> get cron job time from config

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- react4xp.gradle
- use newer version of react4xp (1.0.2)
- move react4xp specific build tasks to separate file
> MIMIR-740: upgrade react4xp

- src/main/resources/lib/dataquery.ts
> MIMIR-758: Wait 30 sec if response code from requests is 429

- src/main/resources/admin/tools/dashboard/dashboard.es6
- src/main/resources/lib/dataquery.ts
- src/main/resources/lib/ssb/dataset/dataset.ts
- src/main/resources/site/parts/highchart/highchart.es6
- Check if datasource mixin is used
- Parse data from repo and send it to HC
Add 'break' on switch test, so last option is not "default".
Remove fetching of logs that take too much time. We will discuss how to properly show logs later.
MIMIR-694
> Make HC use data from repo

- build.gradle
- src/main/resources/admin/tools/dashboard/dashboard.es6
- src/main/resources/admin/tools/dashboard/dashboard.html
- src/main/resources/assets/styles/_dashboard.scss
- src/main/resources/lib/convert/convert.ts
- src/main/resources/react4xp/_entries/Dashboard/Convert.jsx
- src/main/resources/react4xp/_entries/Dashboard/Dashboard.jsx
- src/main/resources/services/convert/convert.es6
- src/main/resources/services/convert/convert.xml
- src/main/resources/services/websocket/websocket.es6
MIMIR-689
Part 1 to keep PRs smaller:
* Tabs in dashboard
* Dashboard Convert React script
* WebSocket Services
* Convert jobs service
* Minimal Convert lib to test socket on/emit
Missing (Part 2):
* Error handling in Convert.jsx
* Converting KeyFigure
* Converting HighChart
* Adding highcharts to services/convert
> Mimir 689 convert hc keyfigure

- src/main/resources/site/content-types/article/article.ts
- src/main/resources/site/content-types/article/article.xml
- Adds Content Selector for articleArchive in the article content type.
> MIMIR-538 articleArchive Content Selector for article

- src/main/resources/lib/klass/municipalities.ts
> Adds check if params is array, ensures only one element is returned.

- gradle.properties
Also trigger Drone build to see if this works
> Try to downgrade versjon target

- src/main/resources/react4xp/_entries/Dashboard/Dashboard.jsx
> MIMIR-653 filter out dataqueries with errors

- src/main/resources/admin/tools/dashboard/dashboard.es6
- src/main/resources/assets/styles/_dashboard.scss
- src/main/resources/lib/convert/convert.ts
- src/main/resources/lib/repo/dataset.ts
- src/main/resources/lib/ssb/dataset/dashboard.ts
- src/main/resources/react4xp/_entries/Dashboard/Convert.jsx
- src/main/resources/react4xp/_entries/Dashboard/Dashboard.jsx
- src/main/resources/react4xp/_entries/Dashboard/DashboardButtons.jsx
- src/main/resources/services/websocket/websocket.es6
> Mimir 729 refresh data in tables button

- src/main/resources/lib/tbml/tbml.ts
> MIMIR-768 tbprocessor error

- src/main/resources/site/content-types/statistics/statistics.ts
- src/main/resources/site/content-types/statistics/statistics.xml
- src/main/resources/site/i18n/phrases.properties
- src/main/resources/site/i18n/phrases_en.properties
- src/main/resources/site/i18n/phrases_no.properties
- src/main/resources/site/parts/relatedStatistics/relatedStatistics.es6
- src/main/resources/site/parts/table/table.es6
- src/main/resources/site/parts/table/table.html
> Mimir 723 view table Part 3

- package-lock.json
- package.json
- src/main/resources/assets/styles/_table.scss
- src/main/resources/lib/ssb/table.ts
- src/main/resources/lib/ssb/utils.es6
- src/main/resources/lib/types/xmlParser.ts
- src/main/resources/react4xp/_entries/Table.jsx
- src/main/resources/site/content-types/table/table.ts
- src/main/resources/site/content-types/table/table.xml
- src/main/resources/site/mixins/sources/sources.ts
- src/main/resources/site/mixins/sources/sources.xml
- src/main/resources/site/parts/highchart/highchart.es6
- src/main/resources/site/parts/infoGraphics/infoGraphics-part-config.ts
- src/main/resources/site/parts/infoGraphics/infoGraphics.es6
- src/main/resources/site/parts/table/table.es6
> Mimir 706 sources and footnotes

- src/main/java/no/ssb/xp/xmlparser/XmlParser.java
- src/main/resources/lib/tbml/tbml.ts
- src/main/resources/lib/types/xmlParser.ts
> MIMIR-788 xml to json fix

- src/main/resources/site/includes/metainfoSearch.html
- src/main/resources/site/pages/default/default.es6
Added metainfo to municipality pages, removed title from metainfo since it uses page title
> Mimir 789 searchable municipal factspage

- package-lock.json
- src/main/resources/site/content-types/accordion/accordion.xml
- src/main/resources/site/content-types/article/article.xml
- src/main/resources/site/content-types/articleArchive/articleArchive.xml
- src/main/resources/site/content-types/highchart/highchart.xml
- src/main/resources/site/content-types/municipalityAlert/municipalityAlert.xml
- src/main/resources/site/content-types/omStatistikken/omStatistikken.xml
- src/main/resources/site/content-types/operationsAlert/operationsAlert.xml
- Superscript
- Subscript
- Strikethrough
- Copy
- Cut
MIMIR-787
> Add actions

- package-lock.json
- src/main/resources/admin/tools/dashboard/dashboard.es6
- src/main/resources/lib/ssb/dataset/dashboard.ts
- src/main/resources/react4xp/_entries/Dashboard/Dashboard.jsx
Edit: This will fix non visible username in dashboard.
> MIMIR-766: Change dashboard to use userstore dynamic

- package-lock.json
- src/main/resources/lib/highcharts/data/htmlTable.es6
- src/main/resources/lib/highcharts/highchartsData.es6
Reformat switched categories and rows
MIMIR-803
> MIMIR-803: Parse result of xmlParser

- package-lock.json
- src/main/resources/site/parts/divider/divider.es6
- src/main/resources/site/parts/divider/divider.html
- src/main/resources/site/parts/menuBox/menuBox.es6
Add clientside rendering for menuBox
Add clientside rendering for Dividers
MIMIR-793
>  MIMIR-793: Add clientside rendering

- package-lock.json
- src/main/resources/lib/highcharts/graph/graphAreaConfig.es6
To get normal y-axis tickintervall the categories must be removed in area charts
> MIMIR-805: Remove categories in y-axis

- src/main/resources/lib/ssb/statisticAlert.es6
- src/main/resources/lib/ssb/utils.es6
- src/main/resources/site/content-types/statisticAlert/statisticAlert.svg
- src/main/resources/site/content-types/statisticAlert/statisticAlert.ts
- src/main/resources/site/content-types/statisticAlert/statisticAlert.xml
- src/main/resources/site/pages/default/default.es6
> MIMIR-799: Add alert for statistic

- src/main/resources/lib/listeners.ts
- src/main/resources/lib/repo/dataset.ts
- src/main/resources/lib/ssb/dataset/dataset.ts
- src/main/resources/lib/ssb/dataset/statbankSaved.ts
- src/main/resources/lib/statBankSaved/statBankSaved.ts
- src/main/resources/site/content-types/genericDataImport/genericDataImport.ts
- src/main/resources/site/content-types/highchart/highchart.ts
- src/main/resources/site/content-types/keyFigure/keyFigure.ts
- src/main/resources/site/content-types/table/table.ts
- src/main/resources/site/mixins/dataSource/dataSource.ts
- src/main/resources/site/mixins/dataSource/dataSource.xml
Add fetch data functions for statbank saved
Change datasource input to support url or id
Add request for html table
Save html and json format of result
MIMIR-780
> MIMIR-780 save data from statbank saved tables to repo

- .drone.yml
> MIMIR-798: Add qa deploy on merge to master

- src/main/resources/lib/ssb/cache.ts
- src/main/resources/lib/ssb/keyFigure.ts
- src/main/resources/lib/ssb/table.ts
- src/main/resources/site/parts/highchart/highchart.es6
Add caching for table, highcharts and keyfigures
Turn on logging for cache
> MIMIR-783 Add cache on data fetch from repo

- src/main/resources/assets/styles/_header.scss
- src/main/resources/lib/ssb/menu.ts
- src/main/resources/lib/ssb/utils.es6
- src/main/resources/react4xp/_entries/Header.jsx
Add support for svg injection
Add rules for old and new icons
> MIMIR-716: Change icon colors on hover

- src/main/resources/assets/styles/main.scss
- src/main/resources/site/pages/default/default.html
Add classname to distinguish top row
Add color and width
MIMIR-772
> MIMIR-772: white background behind breadcrumbs and alerts

- src/main/resources/lib/ssb/keyFigure.ts
- src/main/resources/site/content-types/keyFigure/keyFigure.ts
- src/main/resources/site/content-types/keyFigure/keyFigure.xml
> MIMIR-815 manual source keyfigure

- src/main/resources/react4xp/_entries/Table.jsx
MIMIR-722
Fixes problem where tables that's supposed to have scroll controls doesn't get them until you resize or scroll if they're in an accordion.
> MIMIR-722-scroll-arrow-on-wide-tables

- src/main/resources/site/site.xml
> MIMIR-46 remove dataquery content type in siteconfig

- package-lock.json
- src/main/resources/lib/ssb/dataset/statbankSaved.ts
Remove unused params
Add format to url
> MIMIR-780: Bugfix

- package-lock.json
- src/main/resources/assets/styles/_header.scss
- src/main/resources/lib/highcharts/graph/config.es6
- src/main/resources/lib/ssb/menu.ts
- src/main/resources/lib/ssb/utils.es6
- src/main/resources/react4xp/_entries/Header.jsx
Remove tab index for hidden elements
Let bottomborder stay black on active and focused
Removed double tabindex
Linting
> MIMIR-42: Menu tabbing

- package-lock.json
- src/main/resources/assets/styles/_header.scss
- src/main/resources/lib/highcharts/data/htmlTable.es6
Add code for undefined variable
Add select all selector for menu icons
> Bugfix: x axis linear options break highcharts

- src/main/resources/site/parts/relatedArticles/relatedArticles.es6
Change to undefined to not break array iteration
> MIMIR-75: list disappear when non published articles are in list bugfix

- src/main/resources/lib/ssb/cache.ts
- src/main/resources/lib/ssb/dataset/dashboard.ts
- src/main/resources/lib/ssb/parent.ts
Add new file for parent utils
MIMIR-26
> MIMIR-26: Add caching for parent type iteration

- src/main/resources/assets/styles/_dashboard.scss
- src/main/resources/react4xp/_entries/Dashboard/containers/Statistics/index.jsx
- src/main/resources/site/content-types/statistics/statistics.xml
- src/main/resources/site/parts/statistics/statistics.es6
Fixed sorting of norwegian and english shortname and added som styling
> MIMIR-12: Part 3

- src/main/resources/lib/repo/statreg.ts
- src/main/resources/lib/ssb/statreg/index.ts
- src/main/resources/main.es6
> MIMIR-98-stop-statreg-import-on-startup

- package-lock.json
- src/main/resources/lib/repo/job.ts
- src/main/resources/lib/ssb/cron.ts
- src/main/resources/lib/task.ts
- src/main/resources/lib/types/cron.ts
- src/main/resources/main.es6
> Mimir 104 cronjob user

- src/main/resources/assets/styles/_table.scss
- src/main/resources/react4xp/_entries/Table.jsx
had to add text wrapper div to get correct style
and custom class when col-8 sets 66% max-width also when table is scrollable and has width of 3000+px
> Added max width to table title.

- src/main/resources/site/content-types/statistics/statistics.ts
- src/main/resources/site/content-types/statistics/statistics.xml
- src/main/resources/site/parts/statistics/statistics.es6
also cleaned up controller to work with new xml
> added option-set to content-type

- src/main/resources/lib/ssb/dataset/publish.ts
> MIMIR-15 take in serveroffset for publishing

- package-lock.json
- src/main/resources/lib/repo/dataset.ts
- src/main/resources/lib/ssb/dataset/dataset.ts
- src/main/resources/lib/ssb/dataset/tbprocessor.ts
- src/main/resources/lib/ssb/keyFigure.ts
- src/main/resources/lib/ssb/statistic.ts
- src/main/resources/lib/statBankSaved/statBankSaved.ts
- src/main/resources/lib/task.ts
- src/main/resources/lib/tbml/tbml.ts
- src/main/resources/lib/types/xmlParser.ts
- src/main/resources/react4xp/_entries/Dashboard/components/RefreshStatisticsForm.jsx
- src/main/resources/react4xp/_entries/Dashboard/containers/Statistics/actions.es6
- src/main/resources/react4xp/_entries/Dashboard/containers/Statistics/index.jsx
- src/main/resources/site/parts/banner/banner.es6
Get sourcelist when registering a new tbml
Merge sourcelist with tbml data
Use sourcelist to show owner in update modal
Group sourcelist on owner id
Enable username and password fields
Send in user, password and owner id to backend
MIMIR-114
> MIMIR-114: Get owner for tbml tables

- src/main/resources/lib/ssb/dataset/dashboard.ts
- src/main/resources/lib/ssb/statistic.ts
- src/main/resources/lib/task.ts
- src/main/resources/react4xp/_entries/Dashboard/containers/HomePage/actions.es6
> MIMIR-103 username in dashboard

- src/main/resources/lib/ssb/statistic.ts
> MIMIR-114: BUGFIX Add check for metadata when fetching sourelist

- package-lock.json
- src/main/resources/react4xp/_entries/Dashboard/containers/DashboardTools/index.jsx
- src/main/resources/react4xp/_entries/Dashboard/containers/DataQueryTools/index.jsx
- src/main/resources/react4xp/_entries/Dashboard/containers/HomePage/index.jsx
- src/main/resources/react4xp/_entries/Dashboard/containers/Statistics/index.jsx
> MIMIR-137 move clear cache over to statistics tab

- package-lock.json
- src/main/resources/lib/ssb/cron.ts
- src/main/resources/lib/ssb/dataset/publish.ts
- src/main/resources/lib/ssb/statistic.ts
> MIMIR-15 bugfix and more logging in publish job

- src/main/resources/lib/ssb/dataset/dataset.ts
- src/main/resources/lib/ssb/dataset/tbprocessor.ts
> MIMIR-150 fetch and use correct language for tbprocessor

- src/main/resources/assets/styles/_404.scss
- src/main/resources/site/error/404.html
fixed mobile view
added link around logo
adjustet title padding
> made changes to 404 page.

- src/main/resources/lib/ssb/statistic.ts
- src/main/resources/react4xp/_entries/Dashboard/containers/DashboardTools/index.jsx
- src/main/resources/react4xp/_entries/Dashboard/containers/Statistics/actions.es6
- src/main/resources/react4xp/_entries/Dashboard/containers/Statistics/index.jsx
- src/main/resources/react4xp/_entries/Dashboard/containers/Statistics/selectors.es6
- src/main/resources/react4xp/_entries/Dashboard/containers/Statistics/slice.es6
> Mimir 135 dashboard statistics search

- src/main/resources/lib/repo/dataset.ts
- src/main/resources/lib/repo/job.ts
- src/main/resources/lib/ssb/dataset/publish.ts
- src/main/resources/lib/ssb/keyFigure.ts
- src/main/resources/lib/ssb/table.ts
- src/main/resources/main.es6
- src/main/resources/site/content-types/omStatistikken/omStatistikken.ts
- src/main/resources/site/parts/attachmentTablesFigures/attachmentTablesFigures.es6
Negate includes checks
Remove argument in interface
Change interface function name to match function
Temporarly remove failing cronjob
MIMIR-220
> MIMIR-220: Bugfixing in startup file (main.es6)

- src/main/resources/site/parts/highchart/highchart.es6
- src/main/resources/site/parts/highchart/highchart.html
Still missing button to swap in unpublished figures but as this is not a react part it would be a bit hacky
> Mimir 144 hc draft preview

- src/main/resources/lib/repo/eventLog.ts
- src/main/resources/lib/repo/job.ts
- src/main/resources/lib/repo/query.ts
- src/main/resources/lib/repo/statreg.ts
- src/main/resources/lib/ssb/cron.ts
- src/main/resources/lib/ssb/dataset/dashboard.ts
- src/main/resources/lib/ssb/eventLog.ts
- src/main/resources/lib/ssb/statreg/index.ts
to stop files from inporting each other into an recursive halt.
Change name to repoEventLib
> MIMIR-28: Place delete expired log code in new file

- src/main/resources/assets/styles/_dashboard.scss
- src/main/resources/lib/repo/job.ts
- src/main/resources/lib/ssb/dataset/dashboard.ts
- src/main/resources/react4xp/_entries/Dashboard/Dashboard.jsx
- src/main/resources/react4xp/_entries/Dashboard/containers/HomePage/index.jsx
- src/main/resources/react4xp/_entries/Dashboard/containers/Jobs/actions.es6
- src/main/resources/react4xp/_entries/Dashboard/containers/Jobs/index.jsx
- src/main/resources/react4xp/_entries/Dashboard/containers/Jobs/listeners.es6
- src/main/resources/react4xp/_entries/Dashboard/containers/Jobs/selectors.es6
- src/main/resources/react4xp/_entries/Dashboard/containers/Jobs/slice.es6
- src/main/resources/react4xp/_entries/Dashboard/store/configureStore.es6
- src/main/resources/react4xp/_entries/Dashboard/utils/websocket/WebsocketProvider.jsx
> MIMIR-136 list cron jobs in dashboard

- src/main/resources/react4xp/_entries/Table.jsx
- src/main/resources/site/content-types/table/table.ts
- src/main/resources/site/mixins/sources/sources.ts
- src/main/resources/site/mixins/sources/sources.xml
- src/main/resources/site/parts/infoGraphics/infoGraphics-part-config.ts
and added checks in table sourcelinks if its filled out
> Made sourcelink required

- src/main/resources/lib/language.es6
added nynorsk to try catch and return
> added nynorsk phrases

- package-lock.json
- src/main/resources/lib/ssb/permissions.ts
- src/main/resources/site/parts/highchart/highchart.es6
- src/main/resources/site/parts/keyFigure/keyFigure.es6
- src/main/resources/site/parts/statistics/statistics.es6
- src/main/resources/site/parts/table/table.es6
> MIMIR-186-preview-unpublished-statistics-with-write-access

- src/main/resources/lib/ssb/cron.ts
> MIMIR-28: Pick up correct mimir-config

- package.json
Instead of upgrading uuid, i removed it from package.json since we dont use it.
> Remove uuid from package.json

- src/main/resources/lib/ssb/dataset/dashboard.ts
- src/main/resources/lib/ssb/dataset/publish.ts
> MIMIR-247-bugfix complete publish job on 0 statistics

- src/main/resources/site/parts/omStatistikken/omStatistikken.es6
- src/main/resources/site/parts/statbankBox/statbankBox.es6
- src/main/resources/site/parts/statbankLinkList/statbankLinkList.es6
- Fixes the issue about the 'Om statistikken' part (including statbankLinkList and statbankBox) using the wrong phrases.
> MIMIR-230 bugfix nynorsk phrases

- src/main/resources/lib/ssb/statistic.ts
> Bugfix: Imports users from correct library

- src/main/resources/lib/ssb/statistic.ts
> Increase count for fetching statistics

- src/main/resources/react4xp/_entries/Dashboard/containers/Statistics/index.jsx
> MIMIR-241 Add statistics in new norwegian to statisticList on dashboard

- src/main/resources/lib/ssb/permissions.ts
> Mimir 186 preview unpublished statistics with write access

- src/main/resources/services/contacts/contacts.es6
added default searchstring so it starts at top if nothing is entered
> contact search failed if undefined

- src/main/resources/lib/ssb/dataset/tbprocessor.ts
> Mimir 264 support links on tbml datasource

- src/main/resources/lib/ssb/dataset/dashboard.ts
- src/main/resources/react4xp/_entries/Dashboard/containers/Jobs/index.jsx
> MIMIR-274 use client local and not server local for job time

- src/main/resources/lib/ssb/statistic.ts
> MIMIR-301 temp fix for statistics logs in dashboard

- src/main/resources/site/parts/statbankBox/statbankBox.es6
- src/main/resources/site/parts/statbankLinkList/statbankLinkList.es6
> Mimir 314 language relative links to statbank

- src/main/resources/react4xp/_entries/Dashboard/containers/DashboardTools/index.jsx
> MIMIR-303-fix-update-published-statistic-from-dashboard

- src/main/resources/lib/ssb/cache.ts
> set cache node listener to localOnly false

- src/main/resources/lib/tbml/tbml.ts
> MIMIR-310: Increase timeout time

- .drone.yml
- .github/workflows/mabl_test.yml
- .github/workflows/merge_mabl_feature_branch.yml
Oppdatert workflow for PR bygg og test
> Mimir 285 workflow scripts

- src/main/resources/site/parts/factBox/factBox.html
A border was added around factBox for testing purposes. This removes the changes.
> Removes border around factBox

- src/main/resources/admin/tools/dashboard/dashboard.html
- src/main/resources/admin/tools/dashboard/dashboard.xml
- src/main/resources/react4xp/_entries/Dashboard/Dashboard.jsx
> MIMIR-374: Remove "desk" from "Dashboard desk"

- src/main/resources/lib/ssb/dataset/dashboard.ts
- src/main/resources/lib/ssb/statistic.ts
> MIMIR-390: Make some ws-feedbacks optional

- src/main/resources/assets/styles/_attachmentTablesFigures.scss
- src/main/resources/react4xp/_entries/AttachmentTablesFigures.jsx
- src/main/resources/site/content-types/statistics/statistics.ts
- src/main/resources/site/content-types/statistics/statistics.xml
- src/main/resources/site/parts/accordion/accordion.jsx
- src/main/resources/site/parts/attachmentTablesFigures/attachmentTablesFigures.es6
- Adds htmlArea field for attachment tables and figures, statistics content type
- Moves code from accordion to AttachmentTablesFigures
- Changes to controller made accordingly, new styling is also added for the free text field
> Mimir 352 free text field attachment tables figures

- package-lock.json
- package.json
This version support enter on searchfield
> MIMIR-174: New version of ssb-component-library 2.0.38

- src/main/resources/assets/styles/_dashboard.scss
- src/main/resources/react4xp/_entries/Dashboard/containers/DataQueries/index.jsx
- src/main/resources/react4xp/_entries/Dashboard/containers/Statistics/index.jsx
> changed style of tabs.

- src/main/resources/lib/repo/statreg/statistics.ts
- src/main/resources/lib/ssb/dataset/dashboard.ts
- src/main/resources/lib/ssb/dataset/publish.ts
- src/main/resources/lib/ssb/statistic.ts
- src/main/resources/lib/ssb/statreg/types.ts
- src/main/resources/react4xp/_entries/Dashboard/Dashboard.jsx
- src/main/resources/react4xp/_entries/Dashboard/components/RefreshStatisticsForm.jsx
- src/main/resources/react4xp/_entries/Dashboard/components/RefreshStatisticsModal.jsx
- src/main/resources/react4xp/_entries/Dashboard/containers/DashboardTools/index.jsx
- src/main/resources/react4xp/_entries/Dashboard/containers/Statistics/actions.es6
- src/main/resources/react4xp/_entries/Dashboard/containers/Statistics/index.jsx
- src/main/resources/react4xp/_entries/Dashboard/containers/Statistics/listeners.es6
- src/main/resources/react4xp/_entries/Dashboard/containers/Statistics/selectors.es6
- src/main/resources/react4xp/_entries/Dashboard/containers/Statistics/slice.es6
MIMIR-400
MIMIR-401
MIMIR-402
MIMIR-403
> PART 1 - Dashboard optimization mimir 400 403

- src/main/resources/site/content-types/article/article.ts
- src/main/resources/site/content-types/statistics/statistics.ts
- src/main/resources/site/pages/default/default.es6
Add new generated files for article and statistics
> BUGFIX: Add clientSide tru on pageContributions for breadcrumbs

- src/main/resources/react4xp/_entries/AttachmentTablesFigures.jsx
- Display none when free text field is empty
> MIMIR 352 free text attachmentTablesFigures class

- src/main/resources/react4xp/_entries/Footer.jsx
- src/main/resources/react4xp/_entries/Header.jsx
- src/main/resources/react4xp/_entries/ListOfArticles.jsx
- src/main/resources/site/parts/accordion/accordion.jsx
- src/main/resources/site/parts/relatedFactPage/relatedFactPage.jsx
> MIMIR-379: Change proptypes to match incoming properties

- src/main/resources/react4xp/_entries/Footer.jsx
- src/main/resources/site/parts/accordion/accordion.jsx
> Mimir 379 eval error on accorion

- src/main/resources/lib/ssb/dataset/publish.ts
> MIMIR-181 clear dataset from cache after publish job

- src/main/resources/site/parts/relatedFactPage/relatedFactPage.es6
Check if contentListItem exist before parsing related content
> MIMIR-349: Addes check on relatedFactpage

- package-lock.json
- src/main/resources/lib/repo/statreg/statistics.ts
- src/main/resources/lib/ssb/cron.ts
- src/main/resources/lib/ssb/dataset/mockUnpublished.ts
- src/main/resources/lib/ssb/statistic.ts
- src/main/resources/lib/tbml/tbml.ts
- src/main/resources/lib/tbml/tbmlMock.ts
> Mimir 432 statistics publish test

- src/main/resources/lib/repo/statreg/statistics.ts
> MIMIR-432 use serveroffset for mimir stat release

- src/main/resources/site/pages/default/default-page-config.ts
- src/main/resources/site/pages/default/default.xml
> MIMIR-348: Add more rows to config

- src/main/resources/lib/repo/statreg/statistics.ts
> MIMIR-432 correct datetime format for statreg mock

- src/main/resources/lib/repo/statreg/statistics.ts
> MIMIR-432 bugfix format and remove serverOffset

- package-lock.json
- package.json
- src/main/resources/lib/repo/common.ts
- src/main/resources/lib/ssb/eventLog.ts
> Mimir 449 delete old logs

- package-lock.json
- src/main/resources/lib/ssb/utils.es6
> MIMIR-405: Filter out variants without previous relses

- src/main/resources/lib/ssb/dataset/dashboard.ts
- src/main/resources/lib/ssb/dataset/publish.ts
> Mimir 460 end publish job with skipped statistics

- src/main/resources/services/ping/ping.es6
> Adds app version, renames xp version

- src/main/resources/site/content-types/article/article.ts
- src/main/resources/site/content-types/statistics/statistics.ts
- src/main/resources/site/pages/default/default.es6
- src/main/resources/site/parts/activeStatistics/activeStatistics-part-config.ts
- src/main/resources/site/parts/endedStatistics/endedStatistics-part-config.ts
Add generated types files
MIMIR-react4Xp
> Turn off client side render on breadcrumbs

- src/main/resources/lib/ssb/dataset/dashboard.ts
- src/main/resources/react4xp/_entries/Dashboard/containers/Jobs/index.jsx
> MIMIR-257 check for result on dataset refresh jobs

- src/main/resources/site/parts/divider/divider.html
> Removes mabl-test-class for divider.

- src/main/resources/react4xp/dashboard/utils/websocket/WebsocketProvider.jsx
Remove connection if ping is not returned
MIMIR-272
> MIMIR-272: Add connection status for ws connections

- src/main/resources/assets/styles/_dashboard.scss
- src/main/resources/lib/ssb/dataset/dashboard.ts
- src/main/resources/lib/types/socket.ts
- src/main/resources/react4xp/_entries/Dashboard.jsx
- src/main/resources/react4xp/dashboard/components/ServerTime.jsx
- src/main/resources/react4xp/dashboard/containers/DashboardTools/index.jsx
- src/main/resources/react4xp/dashboard/containers/DataSources/index.jsx
- src/main/resources/react4xp/dashboard/containers/HomePage/actions.es6
- src/main/resources/react4xp/dashboard/containers/HomePage/index.jsx
- src/main/resources/react4xp/dashboard/containers/HomePage/listeners.es6
- src/main/resources/react4xp/dashboard/containers/HomePage/selectors.es6
- src/main/resources/react4xp/dashboard/containers/HomePage/slice.es6
- src/main/resources/react4xp/dashboard/containers/Statistics/index.jsx
> MIMIR-447 display servertime on dashboard

- src/main/resources/site/i18n/phrases.properties
- src/main/resources/site/i18n/phrases_en.properties
- src/main/resources/site/i18n/phrases_nn.properties
- src/main/resources/site/i18n/phrases_no.properties
- src/main/resources/site/parts/statbankBox/statbankBox.es6
> Adds statbankBox alt title to phrases

- src/main/resources/lib/repo/dataset.ts
- src/main/resources/lib/ssb/cache.ts
- src/main/resources/lib/ssb/dataset/publish.ts
> MIMIR-482 publish dataset async and clear dataset cache

- src/main/resources/assets/styles/_banner.scss
- src/main/resources/site/parts/banner/banner.html
also fixed for kommunefakta which had the same issue
> fixed font size and margin according to sketch

- src/main/resources/react4xp/_entries/Footer.jsx
> Adds additional conditionals for the Footer component

- src/main/resources/lib/ssb/keyFigure.ts
> MIMIR-489 Join array before stringifying it.

- src/main/resources/assets/styles/main.scss
> MIMIR-459 Remove rule that misalign elements in grey area

- src/main/resources/lib/ssb/dataset/publish.ts
> MIMIR-508 log publish job timings

- src/main/resources/lib/ssb/dataset/tbprocessor.ts
> MIMIR-514 fetch sourcelist for new public tables

- src/main/resources/lib/repo/statreg/statistics.ts
- src/main/resources/lib/ssb/statistic.ts
> MIMIR-503 sort variants correctly for dashboard

- build.gradle
> MIMIR-519 add feature toggle lib

- src/main/resources/react4xp/dashboard/containers/Statistics/index.jsx
> MIMIR-515 remove statistics nextRelease filter in dashboard

- src/main/resources/assets/styles/_frontpage.scss
- src/main/resources/react4xp/_entries/FrontpageKeyfigures.jsx
> Adds wrapper and styling for clickable boxes

- src/main/resources/lib/ssb/dataset/dataset.ts
> MIMIR-517 refresh dataset now handles statbankapi correctly

- src/main/resources/site/parts/relatedFactPage/relatedFactPage-part-config.ts
- src/main/resources/site/parts/relatedFactPage/relatedFactPage.es6
- src/main/resources/site/parts/relatedFactPage/relatedFactPage.jsx
- src/main/resources/site/parts/relatedFactPage/relatedFactPage.xml
> Changes method of adding related facts pages

- src/main/resources/lib/ssb/dataset/publish.ts
> MIMIR-543 publish job race condition

- src/main/resources/lib/repo/statreg.ts
- src/main/resources/lib/repo/statreg/contacts.ts
- src/main/resources/lib/repo/statreg/statistics.ts
> MIMIR-271 remove old statreg content code

- src/main/resources/react4xp/dashboard/containers/Statistics/index.jsx
> MIMIR-554 show create release link when release is missing

- src/main/resources/react4xp/dashboard/containers/Statistics/index.jsx
> MIMIR-555 preview and edit link when release is missing

- src/main/resources/site/macros/headerLink/headerLink-config.ts
- src/main/resources/site/macros/headerLink/headerLink.jsx
- src/main/resources/site/macros/headerLink/headerLink.ts
- src/main/resources/site/macros/headerLink/headerLink.xml
> Adds headerLink macro

- src/main/resources/react4xp/_entries/Alerts.jsx
> Wraps alerts with container instead of fragment

- package-lock.json
- package.json
- src/main/resources/react4xp/_entries/KpiCalculator.jsx
- src/main/resources/services/kpi/kpi.ts
> Mimir 577 kpi validate fix

- src/main/resources/lib/ssb/keyFigure.ts
- src/main/resources/site/content-types/keyFigure/keyFigure.ts
- src/main/resources/site/content-types/keyFigure/keyFigure.xml
Change field name
Remove regex
Remove code that converted periods to comma
MIMIR-527
> MIMIR-527 allow text in keyfigure field

- src/main/resources/site/content-types/article/article.ts
- src/main/resources/site/content-types/article/article.xml
> MIMIR-576 articleType metafield on articles

- src/main/resources/site/content-types/article/article.ts
- src/main/resources/site/content-types/article/article.xml
> Show on front page unchecked by default; moves field lower

- src/main/resources/lib/tbml/tbmlMock.ts
> Mimir 568 mimir test tables

- src/main/resources/site/content-types/article/article.ts
- src/main/resources/site/content-types/article/article.xml
- src/main/resources/site/i18n/phrases.properties
- src/main/resources/site/i18n/phrases_en.properties
- src/main/resources/site/i18n/phrases_nn.properties
- src/main/resources/site/i18n/phrases_no.properties
- src/main/resources/site/parts/articleList/articleList.ts
added sorting on priority
added filter by subtopic
> added priority buttons

- build.gradle
> Change wsUtil repo

- src/main/resources/services/contacts/contacts.es6
- src/main/resources/services/statistics/statistics.es6
> MIMIR-602 Update paths

- src/main/resources/lib/ssb/cache/cache.ts
> MIMIR-654 cache problems

- react4xp.gradle
- react4xp.properties
- src/test/resources/lib/ssb/utils/utils-test.es6
Add mocking for /lib/xp/portal
Set caching to 0
> update react4xp gradle library to 1.4.0

- src/main/resources/lib/ssb/cache/cache.ts
> log stacktrace in cacheError

- src/main/resources/lib/types/react4xp.ts
- src/main/resources/site/parts/pubArchiveCalendarLinks/pubArchiveCalendarLinks.es6
- src/main/resources/site/parts/releasedStatistics/releasedStatistics.ts
Add client side rendering on components
> Mimir 669 frontpage components polish

- src/main/resources/react4xp/dashboard/containers/Statistics/actions.es6
> MIMIR-677 always refresh related tables and sourcelist

- src/main/resources/lib/ssb/parts/table.ts
- src/main/resources/react4xp/_entries/Table.jsx
> MIMIR-678-bugfix-table-with-tbml-7994

- src/main/resources/lib/ssb/cron/cron.ts
- src/main/resources/lib/ssb/dataset/listeners.ts
- src/main/resources/lib/ssb/utils/serverLog.ts
> MIMIR-655 debounce dataset refresh

- src/main/resources/assets/styles/_articleList.scss
- src/main/resources/assets/styles/_calculator.scss
also a small fix for calculator
> Article list adjustment

- src/main/resources/assets/styles/_nextStatisticsReleases.scss
and changed css selector after changed from h3 to h2
> fixed padding

- src/main/resources/react4xp/_entries/KpiCalculator.jsx
> MIMIR-697: Change proptype

- src/main/resources/site/parts/profiledBox/profiledBox.es6
> Adds getContent import

- src/main/resources/site/content-types/accordion/accordion.xml
- src/main/resources/site/content-types/article/article.xml
- src/main/resources/site/content-types/articleArchive/articleArchive.xml
- src/main/resources/site/content-types/highchart/highchart.xml
- src/main/resources/site/content-types/municipalityAlert/municipalityAlert.xml
- src/main/resources/site/content-types/omStatistikken/omStatistikken.xml
- src/main/resources/site/content-types/operationsAlert/operationsAlert.xml
- src/main/resources/site/content-types/statisticAlert/statisticAlert.xml
- src/main/resources/site/content-types/statistics/statistics.xml
- src/main/resources/site/parts/relatedKostra/relatedKostra.xml
> MIMIR-675-missing-htmlarea-quote-and-format-buttons

- src/main/resources/assets/styles/_publicationArchive.scss
- src/main/resources/assets/styles/main.scss
- src/main/resources/services/publicationArchive/publicationArchive.ts
- src/main/resources/services/publicationArchive/publicationArchive.xml
- src/main/resources/site/i18n/phrases.properties
- src/main/resources/site/i18n/phrases_en.properties
- src/main/resources/site/i18n/phrases_nn.properties
- src/main/resources/site/parts/publicationArchive/publicationArchive-part-config.ts
- src/main/resources/site/parts/publicationArchive/publicationArchive.jsx
- src/main/resources/site/parts/publicationArchive/publicationArchive.ts
- src/main/resources/site/parts/publicationArchive/publicationArchive.xml
> Mimir 619 publication archive

- src/main/resources/site/parts/nameSearch/nameSearch.jsx
> MIMIR-720 bugfix where nameSearch disappears on 0 results

- src/main/resources/lib/ssb/parts/highcharts/data/htmlTable.ts
- src/main/resources/lib/ssb/parts/highcharts/highchartsData.ts
> MIMIR-733 bugfix highchart pie from tbml and excel

- src/main/resources/assets/js/app/highchart.es6
> MIMIR-725 add formatter to legend for piecharts

- src/main/resources/assets/js/ie.es6
- src/main/resources/site/pages/default/default.es6
- src/main/resources/site/pages/default/default.html
- webpack.clientjs.config.js
> MIMIR-690 add information warning to internet explorer users

- package-lock.json
- package.json
- src/main/resources/react4xp/_entries/variables/VariableCard.jsx
> MIMIR-760-variable-list-error

- src/main/resources/assets/js/ie.es6
- src/main/resources/site/pages/default/default.html
> MIMIR-690 move margin to info-warning box from wrapper

- src/main/resources/lib/ssb/cron/rss.ts
> MIMIR-779 filter out last 2 days from statbank rss

- build.gradle
- src/main/resources/services/news/news.ts
- src/main/resources/services/subjectStructurStatistics/subjectStructurStatistics.ts
> MIMIR-732 encode xml services

- src/main/resources/assets/styles/_statbankSubjectTree.scss
- src/main/resources/site/parts/statbankSubjectTree/statbankSubjectTree.jsx
- src/main/resources/site/parts/statbankSubjectTree/statbankSubjectTree.ts
- src/main/resources/site/parts/statbankSubjectTree/statbankSubjectTree.xml
> Removes title and preface for statbank subject tree part

- build.gradle
> Bump lib-react4xp to 1.7.1

- src/main/resources/lib/ssb/utils/subjectUtils.ts
- src/main/resources/site/parts/statbankSubjectTree/statbankSubjectTree.ts
Add secondary statistics to service emnestruktur and to statbank entry
> Mimir 767 add secondary statistics

- package-lock.json
- package.json
- src/main/resources/assets/styles/_searchResult.scss
- src/main/resources/site/parts/searchResult/searchResultView.jsx
Use property size on search result part
MIMIR-778
> MIMIR-778: Bump ssb-components lib

- src/main/resources/site/content-types/upcomingRelease/upcomingRelease.ts
- src/main/resources/site/content-types/upcomingRelease/upcomingRelease.xml
- src/main/resources/site/parts/upcomingReleases/upcomingReleases.jsx
- src/main/resources/site/parts/upcomingReleases/upcomingReleases.ts
> Mimir 630 selected articles in upcoming releases

- src/main/resources/assets/styles/_frontpage.scss
- src/main/resources/assets/styles/main.scss
> MIMIR-790-frontpage-keyfigures-fix-for-large-resolutions

- src/main/resources/react4xp/dashboard/containers/Statistics/index.jsx
> Removes if check for make refresh button

- src/main/resources/lib/ssb/statreg/statistics.ts
- src/main/resources/lib/ssb/utils/arrayUtils.ts
- src/main/resources/services/news/news.ts
> MIMIR-802-rss-news-statistics-fix

- src/main/resources/react4xp/_entries/BkibolCalculator.jsx
- src/main/resources/react4xp/_entries/KpiCalculator.jsx
- src/main/resources/react4xp/_entries/PifCalculator.jsx
- src/main/resources/site/parts/nameSearch/nameSearch.jsx
> Adds focus on correct element, adds tabindex

- src/main/resources/lib/ssb/cache/cache.ts
- src/main/resources/lib/ssb/cache/partCache.ts
- src/main/resources/lib/ssb/cache/subjectCache.ts
- src/main/resources/lib/ssb/utils/subjectUtils.ts
- src/main/resources/services/subjectStructurStatistics/subjectStructurStatistics.ts
- src/main/resources/site/parts/articleList/articleList.ts
- src/main/resources/site/parts/releasedStatistics/releasedStatistics.ts
- src/main/resources/site/parts/statbankSubjectTree/statbankSubjectTree.ts
- src/main/resources/types.ts
> Mimir 806 frontpage performance

- src/main/resources/assets/styles/_article.scss
> MIMIR-804 change highchart width in article

- src/main/resources/site/macros/highchart/highchart.es6
> MIMIR-804 remove highchart dividers on macro (article)

- src/main/resources/lib/ssb/parts/header.ts
- src/main/resources/lib/ssb/parts/menu.ts
- src/main/resources/site/pages/default/default.es6
> MIMIR-806 fix header cache

- src/main/resources/site/parts/articleList/articleList.jsx
In order to make list of links easier to read for screen readers, hopefully
Can't just use h-tags though, no
Everything is a react component these days
MIMIR-799
> Adds H-tags to article list links

- src/main/resources/assets/styles/_header.scss
> Centers arrow and text vertically in top menu.

- src/main/resources/assets/styles/_header.scss
> Removes css styling for statbank-title

- src/main/resources/site/content-types/menuBox/menuBox.ts
- src/main/resources/site/content-types/menuBox/menuBox.xml
- src/main/resources/site/parts/categoryLinks/categoryLinks-part-config.ts
- src/main/resources/site/parts/categoryLinks/categoryLinks.xml
- src/main/resources/site/parts/menuBox/menuBox-part-config.ts
- src/main/resources/site/parts/menuBox/menuBox.xml
Fixed typos
MIMIR-809
MIMIR-810
> Renamed some content types and parts,

- src/main/resources/site/parts/articleList/articleList.ts
> Mimir 828 bugfix prioritized frontpage articles

- src/main/resources/site/parts/articleList/articleList.ts
Reverts statisticsnorway/mimir#1204
> Revert "Mimir 828 bugfix prioritized frontpage articles"

- src/main/resources/site/content-types/accordion/accordion.xml
- src/main/resources/site/content-types/article/article.xml
- src/main/resources/site/content-types/articleArchive/articleArchive.xml
- src/main/resources/site/content-types/highchart/highchart.xml
- src/main/resources/site/content-types/informationAlert/informationAlert.xml
- src/main/resources/site/content-types/municipalityAlert/municipalityAlert.xml
- src/main/resources/site/content-types/omStatistikken/omStatistikken.xml
- src/main/resources/site/content-types/operationsAlert/operationsAlert.xml
- src/main/resources/site/content-types/statisticAlert/statisticAlert.xml
- src/main/resources/site/content-types/statistics/statistics.xml
- src/main/resources/site/parts/publicationArchive/publicationArchive.xml
- src/main/resources/site/parts/relatedKostra/relatedKostra.xml
> MIMIR-847 add bold, italic, underline to htmlarea

- src/main/resources/site/parts/articleList/articleList.ts
> MIMIR-828 re-add priority on article list and fix doc count

- package-lock.json
- package.json
- src/main/resources/assets/js/app/highchart.es6
- src/main/resources/site/parts/highchart/highchart.ts
> Adds quickfix for highcharts download button

- src/main/resources/site/parts/articleList/articleList.ts
> Remove client side rendering for article list

- src/main/resources/assets/styles/_article.scss
> Decreases spacing for article body elements

- src/main/resources/site/i18n/phrases_nn.properties
> Minor adjustments to bkibol nynorsk phrases

- src/main/resources/site/parts/article/article.jsx
Added to Tittel, Ingress and BodyText
> MIMIR-903:Added searchabletext

- src/main/resources/main.es6
- src/main/resources/site/pages/default/default.html
- src/main/resources/site/pages/default/default.ts
> Add enalyzer script for site and toggle via feature toggling

- src/main/resources/lib/ssb/parts/highcharts/graph/config.es6
> Remove keyboard navigation from highcharts config

- src/main/resources/site/parts/nameSearch/nameSearch.jsx
> Require accessibility module in name graph

- package-lock.json
- package.json
- src/main/resources/assets/js/app/highchart.es6
> Highcharts download xlsx with third party lib

- src/main/resources/lib/ssb/parts/highcharts/graph/config.es6
> Replace highcharts color palette with UU verified ssb colors

- src/main/resources/site/parts/attachmentTablesFigures/attachmentTablesFigures.ts
> Use processHtml on free text field for attachment tables figures

- src/main/resources/assets/js/app/highchart.es6
> Add parseFloat to data value for plot option marker fix

- src/main/resources/react4xp/_entries/KpiCalculator.jsx
- src/main/resources/react4xp/_entries/PifCalculator.jsx
- src/main/resources/site/parts/bkibolCalculator/bkibolCalculator.es6
- src/main/resources/site/parts/husleieCalculator/husleieCalculator.es6
- src/main/resources/site/parts/kpiCalculator/kpiCalculator.es6
- src/main/resources/site/parts/pifCalculator/pifCalculator.es6
Wrong phrase for next publish, and wrong if choosen average last year. Both is fixed
> MIMIR-1065:Fixing bug calculators

- package-lock.json
- src/main/resources/assets/styles/_highchart.scss
- src/main/resources/site/parts/highchart/highchart.html
- src/main/resources/site/parts/highchart/highchart.ts
> Make adjustments to highcharts sources

- src/main/resources/site/parts/statistics/statistics.es6
> Move language out of statistics if check scope

- src/main/resources/lib/ssb/parts/header.ts
- src/main/resources/react4xp/_entries/Header.jsx
- src/main/resources/site/i18n/phrases.properties
- src/main/resources/site/i18n/phrases_en.properties
- src/main/resources/site/i18n/phrases_nn.properties
> Add aria-label to header search

- src/main/resources/lib/ssb/dataset/statbankSaved/statbankSavedRequest.ts
> Replace & special character with its xml entity on the response body

- src/main/resources/site/content-types/accordion/accordion.xml
- src/main/resources/site/content-types/article/article.xml
- src/main/resources/site/content-types/articleArchive/articleArchive.xml
- src/main/resources/site/content-types/calculatorConfig/calculatorConfig.xml
- src/main/resources/site/content-types/keyFigure/keyFigure.xml
- src/main/resources/site/content-types/omStatistikken/omStatistikken.xml
- src/main/resources/site/content-types/operationsAlert/operationsAlert.xml
- src/main/resources/site/content-types/statistics/statistics.xml
- src/main/resources/site/mixins/dataSource/dataSource.xml
- src/main/resources/site/mixins/relatedArticles/relatedArticles.xml
- src/main/resources/site/mixins/relatedExternalLinks/relatedExternalLinks.xml
- src/main/resources/site/mixins/sources/sources.xml
- src/main/resources/site/parts/bkibolCalculator/bkibolCalculator.xml
- src/main/resources/site/parts/husleieCalculator/husleieCalculator.xml
- src/main/resources/site/parts/kpiCalculator/kpiCalculator.xml
- src/main/resources/site/parts/pifCalculator/pifCalculator.xml
- src/main/resources/site/parts/publicationArchive/publicationArchive.xml
- src/main/resources/site/parts/relatedKostra/relatedKostra.xml
Dette problemet kan vi finne på å se flere steder fremoer. Viktig å ikke ha whitespace eller line breaks mellom opening og closing tags i xml
> removed whitespace in xml

- src/main/resources/assets/styles/_relatedFactPage.scss
- src/main/resources/react4xp/_entries/ExternalCards.jsx
> Fix styling for parts related fact page and external cards (bootstrap 5)

- src/main/resources/site/parts/searchResult/searchResultView.jsx
> Add gtag event for date and best bet sorting

- src/main/resources/site/parts/relatedFactPage/relatedFactPage.ts
Fix typo for config conditional
MIMIR-1278
> MIMIR-1278 bugfix related fact pages

- src/main/resources/lib/ssb/dashboard/statistic.ts
> Fetches upcoming publications 31 days ahead of time

- src/main/resources/assets/js/app/highchart.es6
> Globally replace all commas for english highchart tables

- src/main/resources/lib/ssb/utils/variantUtils.ts
To get new releases 08:00 before new data from statreg exist.
> MIMIR-1294: Fixed check if nextRelease is passed

- .github/workflows/deploy_to_qa.yaml
Simple change to update a name reference in the github actiong workflow.
> Fix error in job reference

- src/main/resources/site/parts/articleList/articleList.ts
> Remove caching for article list part; commented out code

- docs/PartRendering.md
- src/main/resources/site/parts/attachmentTablesFigures/attachmentTablesFigures.ts
> Remove client render on attachment tables figures

- src/main/resources/site/parts/searchResult/searchResultView.jsx
Avoid errormessages if contenttype in urlParam dont exist in ContentTypePhrases
> MIMIR-1363:Fixed error on preselected contenttype

- .drone.yml
- .github/workflows/manual_deploy_to_prod.yaml
- .github/workflows/manual_deploy_to_qa.yaml
- .github/workflows/manual_deploy_to_test.yml
- src/main/resources/site/error/404.html
- Fix typos for slack messages on manual deploys
- Add workflow configuration for manual deploy to qa
- Test with download-artifacts for manual deploy to test and qa
- Disable automatic deploy to test with drone
> Github Action yaml tweaks

- src/main/resources/site/pages/default/default.html
> Fixes bad value for async and defer

- src/main/resources/services/nameSearch/nameSearch.ts
Somehow this breaks the search terms with the new http library
> Remove plus signs from query

- src/main/resources/services/mainSubject/mainSubject.ts
> Use filters instead of query string for mainSubject service

- Jenkinsfile
Needed a new version of the CI Docker image. It works now!
> bump jenkinsfile version

- package-lock.json
- package.json
> Bump ssb-component-library from 2.0.74 to 2.0.75

- src/main/resources/lib/ssb/dataset/tbprocessor/tbml.ts
> Increase tbml request connection timeout param from 20s to 50s

- src/main/resources/lib/ssb/cron/cron.ts
- src/main/resources/lib/ssb/repo/statisticVariant.ts
- src/main/resources/site/parts/releasedStatistics/releasedStatistics.ts
only run cronjob on master, get next period if nextReleaseToday
> MIMIR-1551: Fixed bug with wrong period released Statistics

- webpack.config.react4xp.js
Fix Error: Empty or not found: /assets/react4xp/stats.components.json
> Comment out BundleAnalyzerPlugin()

- docs/PartRendering.md
- src/main/resources/site/parts/statbankLinkList/statbankLinkList.ts
> Remove clientRender for statbankLinkList part

- src/main/resources/lib/ssb/repo/common.ts
Bug occurred after upgrading xp to 7.11.3
> MIMIR-1751:Fixed bug with sorting of child eventrepo 

- src/main/resources/lib/ssb/cron/eventLog.ts
> Run delete expire event logs queries in increments

- src/main/resources/site/parts/statistics/statistics.ts
> Clientside render glosssary in statistics

- src/main/resources/site/parts/keyFigure/keyFigure.ts
> Remove error handling in renderPart for keyfigures

- src/main/resources/lib/ssb/utils/nameSearchUtils.ts
- src/main/resources/site/parts/searchResult/searchResult.ts
Avoid searchresult to collapse if namesearch fail
> Improve error handling if nameSearchService dont return status 200

- src/main/resources/site/pages/default/default.html
Removed the script for site improve in default html, now there should only be one script injected from the site improve app itself.
> Removed hardcoded site improve <script> 

- src/main/resources/react4xp/_entries/Footer.jsx
- src/main/resources/react4xp/_entries/KeyFigure.jsx
- src/main/resources/react4xp/_entries/StatisticsCards.jsx
- src/main/resources/react4xp/table/Table.jsx
- src/main/resources/site/parts/article/article.jsx
- src/main/resources/site/parts/relatedFactPage/relatedFactPage.jsx
Same changes av old PR from Ole
> Fix various warnings and errors, usually hidden in prod mode

- .github/workflows/jira_issue_title.yaml
https://github.com/the-wright-jamie/Update-PR-Info-Action
> Add action to add jira issue to pr title

- src/main/resources/assets/styles/_table.scss
- src/main/resources/react4xp/table/Table.jsx
Fixed styling so that spacing in vertical direction is same as before. 
Test both desktop and mobile
> MIMIR-1882 fixed styling links (same as before)

- package.json
[Link to ticket: MIMIR-1906](https://statistics-norway.atlassian.net/browse/MIMIR-1906)
> [MIMIR-1906] Bump component library

- src/main/resources/lib/ssb/parts/publicationArchive.ts
- src/main/resources/lib/ssb/utils/variantUtils.ts
- src/main/resources/site/i18n/phrases.properties
- src/main/resources/site/i18n/phrases_en.properties
- src/main/resources/site/layouts/triple/triple.es6
- src/main/resources/site/parts/upcomingReleases/upcomingReleases.jsx
"Enhanced the calculateQuarter function to correctly display suffixes for the English version."
> mimir-1291 feil i engelsk datoformat publikasjonsarkivet

- src/main/resources/admin/tools/dashboard/dashboard.es6
- src/main/resources/admin/tools/dashboard/dashboard.html
- src/main/resources/react4xp/dashboard/containers/DashboardTools/index.jsx
[Link to ticket: MIMIR-1190](https://statistics-norway.atlassian.net/browse/MIMIR-1190)
> [MIMIR-1190] fix dashboard links

- src/main/resources/lib/ssb/utils/language.ts
MIMIR-1818
[Link to ticket: MIMIR-1818](https://statistics-norway.atlassian.net/browse/MIMIR-1818)
> [MIMIR-1818] Display year to year duration for keyfigures with api as source

- src/main/resources/site/parts/relatedArticles/relatedArticles.ts
[Link to ticket: MIMIR-1847](https://statistics-norway.atlassian.net/browse/MIMIR-1847)
> [MIMIR-1847] showing modified date on relatedArticles mixin

- src/main/resources/site/macros/highchart/highchart.ts
[Link to ticket: MIMIR-1914](https://statistics-norway.atlassian.net/browse/MIMIR-1914)
> [MIMIR-1914] Dont use relative import when importing a file with resolve

- src/main/resources/react4xp/_entries/KeyFigure.jsx
- src/main/resources/react4xp/dashboard/components/RefreshStatisticsForm.jsx
- src/main/resources/react4xp/dashboard/components/RefreshStatisticsModal.jsx
- src/main/resources/react4xp/dashboard/containers/DashboardTools/RefreshStatRegModal.jsx
- src/main/resources/react4xp/dashboard/containers/DataSources/DataSourceLog.jsx
- src/main/resources/react4xp/dashboard/containers/DataSources/DataSourceTable.jsx
- src/main/resources/react4xp/dashboard/containers/DataSources/RefreshDataSourceButton.jsx
- src/main/resources/react4xp/dashboard/containers/Jobs/index.jsx
- src/main/resources/react4xp/dashboard/containers/StatRegDashboard/index.jsx
- src/main/resources/react4xp/dashboard/containers/Statistics/StatisticsLog.jsx
- src/main/resources/react4xp/dashboard/containers/Statistics/index.jsx
- src/main/resources/react4xp/table/Table.jsx
- src/main/resources/site/parts/statistics/statistics.html
[Link to ticket: MIMIR-1913](https://statistics-norway.atlassian.net/browse/MIMIR-1913)
> [MIMIR-1913] Use buttons from component library on dashboard++

- src/main/resources/react4xp/dashboard/utils/websocket/WebsocketProvider.jsx
[Link to ticket: MIMIR-1911](https://statistics-norway.atlassian.net/browse/MIMIR-1911)
> [MIMIR-1911] Mimir 1911 decrease ws ping interval

- src/main/resources/assets/styles/_dashboard.scss
- src/main/resources/react4xp/dashboard/components/ReactTable.jsx
- src/main/resources/react4xp/dashboard/containers/Jobs/index.jsx
[Link to ticket: MIM-1493](https://statistics-norway.atlassian.net/browse/MIM-1493)
> [MIM-1493] added warning icon and colored cell

- src/main/resources/site/filters/router.ts
[Link to ticket: MIM-1659](https://statistics-norway.atlassian.net/browse/MIM-1659)
> [MIM-1659] changed separator in title on "kommunefakta"-pages

- .github/workflows/update_mimir_version_number.yaml
[Link to ticket: MIM-746](https://statistics-norway.atlassian.net/browse/MIM-746)
> [MIM-746] fixed syntax error in update mimir version number yaml

- Jenkinsfile
- src/main/resources/lib/ssb/parts/table.ts
- src/main/resources/site/parts/tbmlPreview/tbmlPreview.html
- src/main/resources/site/parts/tbmlPreview/tbmlPreview.ts
- src/main/resources/site/parts/tbmlPreview/tbmlPreview.xml
[Link to ticket: MIM-746](https://statistics-norway.atlassian.net/browse/MIM-746)
> [MIM-746] Mim 746 tbml preview

- src/main/resources/lib/ssb/utils/nameSearchUtils.ts
- src/main/resources/lib/ssb/utils/textUtils.ts
- src/main/resources/services/nameGraph/nameGraph.ts
I'm assuming replacing only the first instance of matching strings wasn't intended, do let me know if I'm missing something :)
> Use replaceAll for sanitization

- src/main/resources/react4xp/dashboard/containers/Jobs/index.jsx
[Link to ticket: MIM-1493](https://statistics-norway.atlassian.net/browse/MIM-1493)
> [MIM-1493] Dashboard: fixed marked rows on not complete, showing started status

- src/main/resources/react4xp/_entries/PifCalculator.jsx
- src/main/resources/services/pif/pif.ts
[Link to ticket: MIM-1622](https://statistics-norway.atlassian.net/browse/MIM-1622)
> [MIM-1622] Fixed bug in PIF calculator related to yearly average calculations

- src/main/resources/lib/ssb/utils/nameSearchUtils.ts
- src/main/resources/lib/ssb/utils/textUtils.ts
- src/main/resources/services/nameGraph/nameGraph.ts
[Link to ticket: MIM-1665](https://statistics-norway.atlassian.net/browse/MIM-1665)
> [MIM-1665] Mim 1665 fikse replace all ekstern pr

- src/main/resources/assets/styles/_dashboard.scss
- src/main/resources/react4xp/dashboard/components/ConnectionTimeoutModal.jsx
[Link to ticket: MIM-1536](https://statistics-norway.atlassian.net/browse/MIM-1536)
> [MIM-1536] Mim 1536 update disconnected modal description dashboard

- src/main/resources/assets/styles/main.scss
- src/main/resources/site/pages/default/default.html
- src/main/resources/site/pages/default/default.xml
This code adds the option for a new region - Dark 5 (#274247)
Code has been tested locally and works well, no errors in lighthouse or wave
[Link to ticket: MIM-933](https://statistics-norway.atlassian.net/browse/MIM-933)
> [MIM-933] MIM-933

- src/main/resources/site/parts/banner/banner.ts
MIM-1656
[Link to ticket: MIM-1656](https://statistics-norway.atlassian.net/browse/MIM-1656)
> [MIM-1656] Scale image correctly for landing pages

- package-lock.json
- package.json
- src/main/resources/react4xp/_entries/BkibolCalculator.jsx
- src/main/resources/react4xp/_entries/KpiCalculator.jsx
- src/main/resources/react4xp/_entries/PifCalculator.jsx
- src/main/resources/react4xp/table/Table.jsx
- src/main/resources/site/parts/husleieCalculator/husleieCalculator.jsx
- src/main/resources/site/parts/publicationArchive/publicationArchive.jsx
- src/main/resources/site/parts/searchResult/searchResultView.jsx
- src/main/resources/site/parts/staticVisualization/staticVisualization.jsx
[Link to ticket: MIM-787](https://statistics-norway.atlassian.net/browse/MIM-787)
> [MIM-787] Mim 787 bump react number format from 4 to 5

- src/main/resources/assets/styles/main.scss
[Link to ticket: MIM-933](https://statistics-norway.atlassian.net/browse/MIM-933)
> [MIM-933] fixes the text color when darkgrey is selected

- src/main/resources/assets/styles/_globalStyles.scss
- src/main/resources/assets/styles/_richText.scss
- src/main/resources/site/parts/richText/richText.jsx
[Link to ticket: MIM-1429](https://statistics-norway.atlassian.net/browse/MIM-1429)
> [MIM-1429] Unify max width of all types to the max readable width

- src/main/resources/react4xp/_entries/PifCalculator.jsx
[Link to ticket: MIM-1077](https://statistics-norway.atlassian.net/browse/MIM-1077)
> [MIM-1077] improved user feedback for missing data in PIF calculator

- src/main/resources/main.es6
- src/main/resources/site/pages/default/default.ts
- src/main/resources/site/pages/default/default.xml
[Link to ticket: MIM-1355](https://statistics-norway.atlassian.net/browse/MIM-1355)
> [MIM-1355] Mim 1355 hide header behind feature toggling

- src/main/resources/react4xp/_entries/PifCalculator.jsx
- src/main/resources/site/i18n/phrases.properties
- src/main/resources/site/i18n/phrases_en.properties
- src/main/resources/site/i18n/phrases_nn.properties
[Link to ticket: MIM-1697](https://statistics-norway.atlassian.net/browse/MIM-1697)
> [MIM-1697] Improve voiceover for pif calculator

- src/main/resources/site/parts/upcomingReleases/upcomingReleases.jsx
Fix for https://statistics-norway.atlassian.net/browse/MIM-1567?focusedCommentId=38191
> Use correct month

- src/main/resources/site/parts/husleieCalculator/husleieCalculator.jsx
[Link to ticket: MIM-1699](https://statistics-norway.atlassian.net/browse/MIM-1699)
> [MIM-1699] Husleiekalkulator

- src/main/resources/site/parts/upcomingReleases/upcomingReleases.jsx
- src/main/resources/site/parts/upcomingReleases/upcomingReleases.ts
[Link to ticket: MIM-1743](https://statistics-norway.atlassian.net/browse/MIM-1743)
> [MIM-1743] Fix bug in showing upcoming releases

- src/main/resources/lib/ssb/utils/calculatorUtils.ts
- src/main/resources/services/bkibol/bkibol.ts
[Link to ticket: MIM-1687](https://statistics-norway.atlassian.net/browse/MIM-1687)
> [MIM-1687] MIM-1687 BKIBOL phrases fix 

- src/main/resources/site/parts/upcomingReleases/upcomingReleases.jsx
[Link to ticket: MIM-1743](https://statistics-norway.atlassian.net/browse/MIM-1743)
> [MIM-1743] fixed duplicate bug in upcoming releases

- src/main/resources/lib/ssb/rss/statkal.ts
[Link to ticket: MIM-1777](https://statistics-norway.atlassian.net/browse/MIM-1777)
> [MIM-1777] MIM-1777:Byttet fra format til formatDate

- src/main/resources/site/parts/husleieCalculator/husleieCalculator.jsx
[Link to ticket: MIM-1718](https://statistics-norway.atlassian.net/browse/MIM-1718)
> [MIM-1718] voiceover: result is only read once for husleieCalculator

- src/main/resources/main.es6
- src/main/resources/site/pages/default/default.html
- src/main/resources/site/pages/default/default.ts
[Link to ticket: MIM-1716](https://statistics-norway.atlassian.net/browse/MIM-1716)
> [MIM-1716] Removed enalyzer script

- package-lock.json
- package.json
- src/main/resources/assets/styles/main.scss
- src/main/resources/site/parts/articleList/articleList.jsx
- src/main/resources/site/parts/publicationArchive/publicationArchive.jsx
- src/main/resources/site/parts/subjectArticleList/subjectArticleList.jsx
[Link to ticket: MIM-334](https://statistics-norway.atlassian.net/browse/MIM-334)
> [MIM-334] Replace react-truncate with CSS solution

- src/main/resources/site/parts/publicationArchive/publicationArchive.jsx
[Link to ticket: MIM-334](https://statistics-norway.atlassian.net/browse/MIM-334)
> [MIM-334] Add spacing that was removed by mistake

- src/main/resources/assets/styles/_menuBox.scss
[Link to ticket: MIM-1726](https://statistics-norway.atlassian.net/browse/MIM-1726)
> [MIM-1726] fixed height issue for menuBox

- src/main/resources/react4xp/_entries/RelatedArticles.jsx
- src/main/resources/site/parts/relatedArticles/relatedArticles.ts
[Link to ticket: MIM-1823](https://statistics-norway.atlassian.net/browse/MIM-1823)
> [MIM-1823] MIM-1823-Related-Articles-alt-image-tag

- src/main/resources/assets/js/app/highchart.es6
- src/main/resources/site/content-types/highchart/highchart.xml
- src/main/resources/site/parts/highchart/Highchart.jsx
- src/main/resources/site/parts/highchartExpert/HighchartExpert.jsx
- src/main/resources/site/parts/highmap/Highmap.jsx
- src/main/resources/site/parts/nameSearch/nameSearch.jsx
[Link to ticket: MIM-1765](https://statistics-norway.atlassian.net/browse/MIM-1765)
> [MIM-1765] Make title for axises on highchart required

- src/main/resources/assets/js/app/highchart.es6
[Link to ticket: MIM-1761](https://statistics-norway.atlassian.net/browse/MIM-1761)
> [MIM-1761] If stolpe or liggende reverse stack order

- src/main/resources/site/parts/articleArchive/articleArchive.ts
[Link to ticket: MIM-1782](https://statistics-norway.atlassian.net/browse/MIM-1782)
> [MIM-1782] Mim 1782 correct article type on discussion paper page

- src/main/resources/main.es6
- src/main/resources/site/pages/default/default.html
- src/main/resources/site/pages/default/default.ts
[Link to ticket: MIM-1818](https://statistics-norway.atlassian.net/browse/MIM-1818)
> [MIM-1818] Remove snapengage chat script

- src/main/resources/lib/ssb/utils/articleUtils.ts
[Link to ticket: MIM-518](https://statistics-norway.atlassian.net/browse/MIM-518)
> [MIM-518] added paths for innrapportering, omssb and forskning for solr indexing

- docs/React4xp.md
- package-lock.json
- package.json
- src/main/resources/lib/ssb/utils/htmlUtils.ts
- src/main/resources/react4xp/_entries/Alerts.jsx
- src/main/resources/react4xp/_entries/ArticleArchive.jsx
- src/main/resources/react4xp/_entries/AttachmentTablesFigures.jsx
- src/main/resources/react4xp/_entries/EntryLinks.jsx
- src/main/resources/react4xp/_entries/FactBox.jsx
- src/main/resources/react4xp/_entries/Header.jsx
- src/main/resources/react4xp/_entries/KpiCalculator.jsx
- src/main/resources/react4xp/_entries/ModifiedDate.jsx
- src/main/resources/react4xp/_entries/StatbankLinkList.jsx
- src/main/resources/react4xp/accordion/Accordion.jsx
- src/main/resources/site/parts/article/article.jsx
- src/main/resources/site/parts/employee/employee.jsx
- src/main/resources/site/parts/employeeList/employeeList.jsx
- src/main/resources/site/parts/nameSearch/nameSearch.jsx
- src/main/resources/site/parts/project/project.jsx
- src/main/resources/site/parts/publicationArchive/publicationArchive.jsx
- src/main/resources/site/parts/relatedKostra/relatedKostra.jsx
- src/main/resources/site/parts/richText/richText.jsx
- src/main/resources/site/parts/searchResult/searchResultView.jsx
- src/main/resources/site/parts/upcomingReleases/upcomingReleases.jsx
- webpack.config.react4xp.js
[Link to ticket: MIM-1781](https://statistics-norway.atlassian.net/browse/MIM-1781)
Tested about 70% of the places it was used. No issues, and implemented the same way on the last 30%.
> [MIM-1781] Mim 1781 Sanitization

- gradle.properties
- src/main/resources/react4xp/_entries/AttachmentTablesFigures.jsx
Temporarily remove sanitizing on highcharts HTML until we can correctly configure it
> Deploye mimir 2.4.1

- src/main/resources/site/content-types/highmap/highmap.xml
- src/main/resources/site/parts/highmap/Highmap.jsx
- src/main/resources/site/parts/highmap/highmap.ts
[Link to ticket: MIM-1750](https://statistics-norway.atlassian.net/browse/MIM-1750)
> [MIM-1750] Make thresholds optional. Allow mapdata in second column

- src/main/resources/lib/ssb/parts/highcharts/graph/config.ts
- src/main/resources/site/content-types/highchart/highchart.xml
Reverted changes done in this PR: https://github.com/statisticsnorway/mimir/pull/2544
[Link to ticket: MIM-1732](https://statistics-norway.atlassian.net/browse/MIM-1732)
> [MIM-1732] reverted changes for highchart config

- src/main/resources/lib/ssb/parts/highcharts/data/htmlTable.ts
[Link to ticket: MIM-1766](https://statistics-norway.atlassian.net/browse/MIM-1766)
> [MIM-1766] Replace all spaces instead of just one when parsing value from html table

- src/main/resources/site/parts/highmap/Highmap.jsx
[Link to ticket: MIM-1755](https://statistics-norway.atlassian.net/browse/MIM-1755)
> [MIM-1755] MIM-1755 Added sources to export Highmap.jsx

- src/main/resources/lib/ssb/parts/highcharts/highchartsGraphConfig.ts
- src/main/resources/site/content-types/combinedGraph/combinedGraph.xml
[Link to ticket: MIM-1727](https://statistics-norway.atlassian.net/browse/MIM-1727)
> [MIM-1727] MIM-1727:Lagt til offset for Y-akse

- src/main/resources/site/content-types/simpleStatbank/simpleStatbank.xml
- src/main/resources/site/macros/simpleStatbank/simpleStatbank.ts
- src/main/resources/site/macros/simpleStatbank/simpleStatbank.xml
- src/main/resources/site/pages/default/default.ts
- src/main/resources/site/parts/simpleStatbank/simpleStatbank.ts
- src/main/resources/site/parts/simpleStatbank/simpleStatbank.xml
[Link to ticket: MIM-1724](https://statistics-norway.atlassian.net/browse/MIM-1724)
> [MIM-1724] Mim 1724 simple query contenttype

- src/main/resources/lib/ssb/cron/cron.ts
[Link to ticket: MIM-783](https://statistics-norway.atlassian.net/browse/MIM-783)
> [MIM-783] Enable test logger

- src/main/resources/site/parts/article/article.ts
- src/main/resources/site/parts/articleList/articleList.ts
- src/main/resources/site/parts/banner/banner.ts
- src/main/resources/site/parts/categoryLinks/categoryLinks.ts
- src/main/resources/site/parts/downloadLink/downloadLink.ts
- src/main/resources/site/parts/employeeList/employeeList.ts
- src/main/resources/site/parts/entryLinks/entryLinks.ts
- src/main/resources/site/parts/externalCard/externalCard.ts
- src/main/resources/site/parts/frontpageKeyfigures/frontpageKeyfigures.ts
- src/main/resources/site/parts/infoGraphics/infoGraphics.ts
- src/main/resources/site/parts/menuBox/menuBox.ts
- src/main/resources/site/parts/pictureCardLinks/pictureCardLinks.ts
- src/main/resources/site/parts/profiledBox/profiledBox.ts
- src/main/resources/site/parts/profiledLinkIcon/profiledLinkIcon.ts
- src/main/resources/site/parts/pubArchiveCalendarLinks/pubArchiveCalendarLinks.ts
- src/main/resources/site/parts/relatedExternalLinks/relatedExternalLinks.ts
- src/main/resources/site/parts/relatedKostra/relatedKostra.ts
- src/main/resources/site/parts/releasedStatistics/releasedStatistics.ts
- src/main/resources/site/parts/statbankBox/statbankBox.ts
- src/main/resources/site/parts/statbankFrame/statbankFrame.ts
- src/main/resources/site/parts/statbankLinkList/statbankLinkList.ts
- src/main/resources/site/parts/variables/variables.ts
https://github.com/statisticsnorway/mimir/blob/develop/docs/PartRendering.md
> Turn off hydration for parts that do not have functionality

- src/main/resources/site/macros/table/table.ts
- src/main/resources/site/macros/table/table.xml
[Link to ticket: MIM-1841](https://statistics-norway.atlassian.net/browse/MIM-1841)
> [MIM-1841] MIM-1841 table macro

- docs/Highmaps.md
- docs/PerformanceIssues.md
- src/main/resources/site/content-types/highmap/highmap.xml
- src/main/resources/site/parts/highmap/Highmap.jsx
[Link to ticket: MIM-1751](https://statistics-norway.atlassian.net/browse/MIM-1751)
> [MIM-1751] Add color stops to gradient color option

- src/main/resources/lib/ssb/rss/statkal.ts
- src/main/resources/services/news/news.ts
Changed variable name to avoid misunderstandings.
> changed from minutes to milliseconds

- src/main/resources/lib/ssb/utils/htmlUtils.ts
[Link to ticket: MIM-1886](https://statistics-norway.atlassian.net/browse/MIM-1886)
> [MIM-1886] allow name and id for a tags when sanitising 

- src/main/resources/assets/styles/_simpleStatbank.scss
- src/main/resources/site/content-types/simpleStatbank/simpleStatbank.xml
- src/main/resources/site/macros/simpleStatbank/simpleStatbank.xml
- src/main/resources/site/parts/simpleStatbank/simpleStatbank.ts
- src/main/resources/site/parts/simpleStatbank/simpleStatbank.tsx
- src/main/resources/site/parts/simpleStatbank/simpleStatbank.xml
[Link to ticket: MIM-1819](https://statistics-norway.atlassian.net/browse/MIM-1819)
> [MIM-1819] MIM-1819:Satt vidde til 100% og endret visningsnavn

- src/main/resources/lib/ssb/cron/rss.ts
Lagt til informasjon om tabeller fra rss og justert litt på tidsrammen den filterer på slik at det blir 2 dager den sjekker
[Link to ticket: MIM-1885](https://statistics-norway.atlassian.net/browse/MIM-1885)
> [MIM-1885] Ryddet i jobbloggen

- src/main/resources/lib/ssb/dataset/statbankApi/statbankApi.ts
- src/main/resources/lib/ssb/utils/datasetUtils.ts
[Link to ticket: MIM-1861](https://statistics-norway.atlassian.net/browse/MIM-1861)
> [MIM-1861] MIM-1861-minibank-region-fix filtering should now work as intended

- src/main/resources/site/content-types/highmap/highmap.xml
- src/main/resources/site/parts/highmap/Highmap.jsx
[Link to ticket: MIM-1751](https://statistics-norway.atlassian.net/browse/MIM-1751)
> [MIM-1751] Fix mellomfarge på highmap

- src/main/resources/admin/tools/dashboard/dashboard.es6
- src/main/resources/react4xp/_entries/DashboardEntry.tsx
- src/main/resources/react4xp/dashboard/containers/DashboardTools/index.tsx
- src/main/resources/react4xp/dashboard/containers/HomePage/selectors.es6
- src/main/resources/react4xp/dashboard/containers/HomePage/slice.es6
[Link to ticket: MIM-1906](https://statistics-norway.atlassian.net/browse/MIM-1906)
> [MIM-1906] Fix link for statregRapport on dashboard

- src/main/resources/lib/ssb/parts/highcharts/highchartsGraphConfig.ts
[Link to ticket: MIM-1884](https://statistics-norway.atlassian.net/browse/MIM-1884)
> [MIM-1884] Remove markers on line graphs on combinedGraph

- .github/workflows/deploy_to_prod.yaml
- .github/workflows/former_build_deploy_to_prod.yaml
- .github/workflows/former_build_deploy_to_qa.yaml
Trenger dette for å kunne skille mellom ulike deployments i jira.
> Update github environment name for deploy

- src/main/resources/main.es6
- src/main/resources/site/parts/simpleStatbank/simpleStatbank.ts
[Link to ticket: MIM-1867](https://statistics-norway.atlassian.net/browse/MIM-1867)
> [MIM-1867] Removed featureToggle for simpleStatbank from code

- src/main/resources/assets/styles/_keyFigures.scss
- src/main/resources/site/macros/keyFigure/keyFigure.ts
- src/main/resources/site/macros/keyFigure/keyFigure.xml
[Link to ticket: MIM-1915](https://statistics-norway.atlassian.net/browse/MIM-1915)
> [MIM-1915] Added macro config for keyFigure

- src/main/resources/site/pages/default/default.html
[Link to ticket: MIM-1887](https://statistics-norway.atlassian.net/browse/MIM-1887)
> [MIM-1887] Mim 1887 removal of universal analytics

- src/main/resources/site/pages/default/default.html
Trying to remedy mabl failures inside i.test
[Test highmap and highchart from excel](https://app.mabl.com/workspaces/kbq2IgbyWwSngpWi8JPrXw-w/train/tests/AqLLSeekQBsxOdpbp7A2mA-j/test-runs/YIclnLmmoDz2CvlnrhhWKA-jr)
[Test highchart from API & TBML](https://app.mabl.com/workspaces/kbq2IgbyWwSngpWi8JPrXw-w/train/tests/qLFBM7hnGIHtLmW2aXmirQ-j/test-runs/Fy0kQ4EN2ureLtcB05WKSg-jr)
need to rollback past QA changes in : https://github.com/statisticsnorway/mimir/actions/runs/9298483928
> [MIM-1887] UA script for TEST

- src/main/resources/main.es6
- src/main/resources/site/pages/default/default.html
- src/main/resources/site/pages/default/default.ts
[Link to ticket: MIM-1894](https://statistics-norway.atlassian.net/browse/MIM-1894)
> [MIM-1894] Mim 1894 add page map structured data

- src/main/resources/lib/ssb/parts/highcharts/graph/config.ts
[Link to ticket: MIM-1970](https://statistics-norway.atlassian.net/browse/MIM-1970)
> [MIM-1970] Added responsive config for right y axis in highcharts

- src/main/resources/assets/styles/_article.scss
- src/main/resources/assets/styles/_globalStyles.scss
[Link to ticket: MIM-1904](https://statistics-norway.atlassian.net/browse/MIM-1904)
> [MIM-1904] Add global styling for line-height for lists

- src/main/resources/lib/ssb/utils/dateUtils.ts
- src/main/resources/site/parts/article/article.ts
- src/main/resources/site/parts/statistics/statistics.ts
Remove seconds in date format (e.g. 08:00 instead of 08:00:00)
MIM-1763
[Link to ticket: MIM-1763](https://statistics-norway.atlassian.net/browse/MIM-1763)
> [MIM-1763] Change date format for modified date for article and statistics

- src/main/resources/react4xp/dashboard/store/configureStore.es6
- src/main/resources/site/i18n/phrases.properties
- src/main/resources/site/i18n/phrases_en.properties
- src/main/resources/site/i18n/phrases_nn.properties
- src/main/resources/site/parts/omStatistikken/omStatistikken.tsx
[Link to ticket: MIM-1971](https://statistics-norway.atlassian.net/browse/MIM-1971)
> [MIM-1971] Fixed texts in om statistikken

- src/main/resources/lib/ssb/parts/highcharts/graph/config.ts
- src/main/resources/lib/ssb/parts/highcharts/graph/graphBarNegativeConfig.ts
[Link to ticket: MIM-1973](https://statistics-norway.atlassian.net/browse/MIM-1973)
> [MIM-1973] added custom responsive config to barNegativeConfig

- src/main/resources/site/content-types/statistics/statistics.xml
- src/main/resources/site/parts/statistics/statistics.ts
[Link to ticket: MIM-1762](https://statistics-norway.atlassian.net/browse/MIM-1762)
> [MIM-1762] Add checkbox  to toggle time for modified date for statistics

- src/main/resources/lib/ssb/utils/nameSearchUtils.ts
- src/main/resources/site/parts/nameSearch/nameSearch.jsx
[Link to ticket: MIM-1956](https://statistics-norway.atlassian.net/browse/MIM-1956)
> [MIM-1956] Remove replaceCharacters, update allow list in backend + frontend

- src/main/resources/site/parts/mailChimpForm/mailChimpForm.xml
MIM-1995
[Link to ticket: MIM-1995](https://statistics-norway.atlassian.net/browse/MIM-1995)
> [MIM-1995] Rename newsletter form url input name

- src/main/resources/site/parts/highmap/Highmap.jsx
- src/main/resources/site/parts/highmap/highmap.ts
MIM-1997
[Link to ticket: MIM-1997](https://statistics-norway.atlassian.net/browse/MIM-1997)
> [MIM-1997] Wrap highmap part body in section for spacing

- src/main/resources/lib/ssb/parts/keyFigure.ts
- src/main/resources/lib/types/partTypes/keyFigure.ts
- src/main/resources/site/i18n/phrases.properties
- src/main/resources/site/i18n/phrases_en.properties
- src/main/resources/site/i18n/phrases_nn.properties
- src/main/resources/site/pages/default/default.ts
[Link to ticket: MIM-1932](https://statistics-norway.atlassian.net/browse/MIM-1932)
> [MIM-1932] Mim 1932 sr arrow keyfigure

- src/main/resources/lib/types/article.ts
- src/main/resources/react4xp/_entries/BkibolCalculator.tsx
- src/main/resources/react4xp/_entries/KpiCalculator.tsx
- src/main/resources/react4xp/_entries/PifCalculator.tsx
- src/main/resources/site/parts/contactForm/contactForm.tsx
- src/main/resources/site/parts/searchResult/searchResultView.tsx
- src/main/resources/site/parts/subjectArticleList/subjectArticleList.tsx
[Link to ticket: MIM-2020](https://statistics-norway.atlassian.net/browse/MIM-2020)
> [MIM-2020] Mim 2020 bugfix pre selected dropdown item

- src/main/resources/react4xp/_entries/PifCalculator.tsx
[Link to ticket: MIM-2020](https://statistics-norway.atlassian.net/browse/MIM-2020)
> [MIM-2020] Mim 2020 bugfix pif calculator dropdown options

- src/main/resources/assets/styles/_upcomingReleases.scss
- src/main/resources/lib/ssb/utils/filterReleasesUtils.ts
- src/main/resources/lib/types/partTypes/upcomingReleases.ts
- src/main/resources/lib/types/variants.ts
- src/main/resources/services/upcomingReleases/upcomingReleases.ts
- src/main/resources/site/i18n/phrases.properties
- src/main/resources/site/i18n/phrases_en.properties
- src/main/resources/site/i18n/phrases_nn.properties
- src/main/resources/site/parts/upcomingReleases/upcomingReleases.ts
- src/main/resources/site/parts/upcomingReleases/upcomingReleases.tsx
[Link to ticket: MIM-1935](https://statistics-norway.atlassian.net/browse/MIM-1935)
> [MIM-1935] Mim 1935 upcoming releases adjustments to statistics urls

- package-lock.json
- package.json
- src/main/resources/lib/ssb/utils/utils.ts
- src/main/resources/lib/types/partTypes/profiledBox.ts
- src/main/resources/lib/types/partTypes/relatedArticles.ts
- src/main/resources/react4xp/_entries/RelatedArticles.tsx
- src/main/resources/site/parts/profiledBox/profiledBox.ts
- src/main/resources/site/parts/profiledBox/profiledBox.tsx
- src/main/resources/site/parts/relatedArticles/relatedArticles.ts
[Link to ticket: MIM-1936](https://statistics-norway.atlassian.net/browse/MIM-1936)
> [MIM-1936] Mim 1936 screen reader text profiled box related articles

- package-lock.json
- package.json
- src/main/resources/assets/styles/_table.scss
- src/main/resources/react4xp/table/Table.tsx
[Link to ticket: MIM-1974](https://statistics-norway.atlassian.net/browse/MIM-1974)
> [MIM-1974] MIM-1974-Table-Component-XP

- src/main/resources/assets/styles/_upcomingReleases.scss
- src/main/resources/site/parts/upcomingReleases/upcomingReleases.tsx
[Link to ticket: MIM-1938](https://statistics-norway.atlassian.net/browse/MIM-1938)
> [MIM-1938] Mim 1938 date div upcoming release

- src/main/resources/react4xp/_entries/ReleasedStatistics.tsx
MIM-1938
[Link to ticket: MIM-1938](https://statistics-norway.atlassian.net/browse/MIM-1938)
> [MIM-1938] Fix date box view for released statistics part

- src/main/resources/react4xp/_entries/BkibolCalculator.tsx
MIM-1988
[Link to ticket: MIM-1988](https://statistics-norway.atlassian.net/browse/MIM-1988)
> [MIM-1988] Fix error message for month validation for BkibolCalculator

- src/main/resources/assets/js/app/highchart.es6
- src/main/resources/assets/styles/_table.scss
[Link to ticket: MIM-2034](https://statistics-norway.atlassian.net/browse/MIM-2034)
> [MIM-2034] Integration of new table in highchart

- docs/React4xp.md
- src/main/resources/lib/types/partTypes/accordion.ts
- src/main/resources/lib/types/partTypes/keyFigure.ts
- src/main/resources/react4xp/_entries/CategoryLinks.tsx
- src/main/resources/react4xp/_entries/EntryLinks.tsx
- src/main/resources/react4xp/_entries/Footer.tsx
- src/main/resources/react4xp/_entries/KeyFigure.tsx
- src/main/resources/react4xp/_entries/ReleasedStatistics.tsx
- src/main/resources/react4xp/_entries/StatbankBox.tsx
- src/main/resources/react4xp/_entries/StatisticsCards.tsx
- src/main/resources/react4xp/accordion/Accordion.tsx
- src/main/resources/react4xp/variables/VariableCard.tsx
- src/main/resources/react4xp/variables/VariableCardsList.tsx
- src/main/resources/site/parts/localSearch/localSearch.tsx
- src/main/resources/site/parts/relatedKostra/relatedKostra.tsx
[Link to ticket: MIM-1948](https://statistics-norway.atlassian.net/browse/MIM-1948)
> [MIM-1948] Mim 1948 classes to functional react parts

- src/main/resources/site/includes/metainfoSearch.html
- src/main/resources/site/pages/default/default.ts
[Link to ticket: MIM-1894](https://statistics-norway.atlassian.net/browse/MIM-1894)
> [MIM-1894] Hotfix mim 1894 improve page map

- package-lock.json
- package.json
- src/main/resources/site/parts/staticVisualization/staticVisualization.tsx
MIM-2034
[Link to ticket: MIM-2034](https://statistics-norway.atlassian.net/browse/MIM-2034)
> [MIM-2034] Use new Table component for static visualization

- src/main/resources/lib/ssb/parts/footer.ts
- src/main/resources/lib/types/footer.ts
- src/main/resources/react4xp/_entries/Footer.tsx
- src/main/resources/site/content-types/footer/footer.xml
MIM-2042
[Link to ticket: MIM-2042](https://statistics-norway.atlassian.net/browse/MIM-2042)
> [MIM-2042] Add instagram social link to footer

- .github/workflows/delete_nais.yaml
- .github/workflows/deploy_nais.yaml
- .github/workflows/update_mimir_version_number.yaml
- nais.yaml
> Changing staging to test nais

- src/main/resources/lib/ssb/parts/simpleStatbank.ts
- src/main/resources/lib/types/partTypes/simpleStatbank.ts
- src/main/resources/site/content-types/simpleStatbank/simpleStatbank.xml
- src/main/resources/site/parts/simpleStatbank/simpleStatbank.ts
- src/main/resources/site/parts/simpleStatbank/simpleStatbank.tsx
[Link to ticket: MIM-1951](https://statistics-norway.atlassian.net/browse/MIM-1951)
> [MIM-1951] Mim 1951 mini statbank variable results

- src/main/resources/lib/ssb/cron/pushRss.ts
- src/main/resources/lib/ssb/cron/rss.ts
- src/main/resources/lib/ssb/dashboard/dashboard.ts
- src/main/resources/lib/ssb/repo/job.ts
- src/main/resources/react4xp/dashboard/containers/DashboardTools/index.tsx
- src/main/resources/react4xp/dashboard/containers/Jobs/index.tsx
- src/main/resources/tasks/pushRssNews/pushRssNews.ts
- src/main/resources/tasks/pushRssStatkal/pushRssStatkal.ts
[Link to ticket: MIM-2039](https://statistics-norway.atlassian.net/browse/MIM-2039)
> [MIM-2039] Mim 2039 rss joblog error view

- src/main/resources/react4xp/_entries/ArticleArchive.tsx
[Link to ticket: MIM-801](https://statistics-norway.atlassian.net/browse/MIM-801)
> [MIM-801] ArticleArchive image 

- .github/workflows/delete_nais.yaml
> [MIM-2005] delete_nais.yaml updates

- .github/workflows/delete_nais.yaml
> [MIM-2005] ssbno back to ssb

- .github/workflows/delete_nais.yaml
> [MIM-2005] Mim 2005 nais alterations 2

- .github/workflows/delete_nais.yaml
> [MIM-2005] TTL 0

- .github/workflows/delete_nais.yaml
- src/main/resources/react4xp/_entries/AttachmentTablesFigures.tsx
> [MIM-2005] MIM-2005-nais-deploy-test-5

- .github/workflows/delete_nais.yaml
> [MIM-2005] MIM-2005-alteration-to-delete-nais

- .github/workflows/delete_nais.yaml
- nais.yaml
> MIM-2005-nais-sed-test

- .github/workflows/delete_nais.yaml
> [MIM-2005] MIM-2005-nais-deploy-test-7

- nais.yaml
> [MIM-2005] Change back to original nais.yaml

- .github/workflows/delete_nais.yaml
> [MIM-2005] MIM-2005-proper-nais-alterations-2

- .github/workflows/delete_nais.yaml
> [MIM-2005] MIM-2005-proper-nais-alterations-3

- .github/workflows/delete_nais.yaml
> [MIM-2005] MIM-2005-proper-nais-ttl-changes

- .github/workflows/delete_nais.yaml
> [MIM-2005] nais delete - Use same image as the orignal PR

- .github/workflows/delete_nais.yaml
- .github/workflows/deploy_nais.yaml
> [MIM-2005] nais using artifact registry for image name across jobs

- docs/Testing.md
> [MIM-2005] Add some Nais feature deploy documentation

- .github/workflows/deploy_nais.yaml
> [MIM-2005] remove branch name test, need to trigger PR close on develop

- docs/Testing.md
> [MIM-2005] add change, to test deployment flow

- src/main/resources/react4xp/_entries/Popup.tsx
- src/main/resources/site/pages/default/default.ts
[Link to ticket: MIM-2066](https://statistics-norway.atlassian.net/browse/MIM-2066)
> [MIM-2066] Visibility check based on cookie set in frontend (POPUP)

- src/main/resources/react4xp/_entries/Popup.tsx
[Link to ticket: MIM-2066](https://statistics-norway.atlassian.net/browse/MIM-2066)
> [MIM-2066] Accessibility fix for popup

- src/main/resources/react4xp/_entries/Popup.tsx
[Link to ticket: MIM-2066](https://statistics-norway.atlassian.net/browse/MIM-2066)
> [MIM-2066] POPUP - accessibility

- src/main/resources/react4xp/_entries/Breadcrumb.tsx
[Link to ticket: MIM-2040](https://statistics-norway.atlassian.net/browse/MIM-2040)
> [MIM-2040] MIM-2040-Breadcrumb-mobileCompressedView

- package-lock.json
- package.json
[Link to ticket: MIM-2040](https://statistics-norway.atlassian.net/browse/MIM-2040)
> [MIM-2040] 2.4.1 -ssb-component-library-update

- .github/workflows/deploy_nais.yaml
- nais.yaml
[Link to ticket: MIM-2006](https://statistics-norway.atlassian.net/browse/MIM-2006)
> [MIM-2006] Add url to PR comment test

- .github/workflows/deploy_nais.yaml
- nais.yaml
[Link to ticket: MIM-2006](https://statistics-norway.atlassian.net/browse/MIM-2006)
> [MIM-2006] Test commit for deploy

- .github/workflows/deploy_nais.yaml
- nais.yaml
[Link to ticket: MIM-2006](https://statistics-norway.atlassian.net/browse/MIM-2006)
> [MIM-2006] Add test commit for PR

- .github/workflows/deploy_nais.yaml
- .github/workflows/jira_issue_title.yaml
[Link to ticket: MIM-2006](https://statistics-norway.atlassian.net/browse/MIM-2006)
[🗄️ Link to branch admin interface!](https://ssbno-mim-2006.intern.test.ssb.no/admin)
[📰 Front page can be found here!](https://ssbno-mim-2006.intern.test.ssb.no/)
> [MIM-2006] Improve branch deploy comment on PR

- package-lock.json
- package.json
[Link to ticket: MIM-2040](https://statistics-norway.atlassian.net/browse/MIM-2040)
> [MIM-2040] SSB-Component-Library update 2.4.2

- src/main/resources/lib/ssb/utils/nameSearchUtils.ts
- src/main/resources/site/parts/nameSearch/nameSearch.jsx
[Link to ticket: MIM-2082](https://statistics-norway.atlassian.net/browse/MIM-2082)
> [MIM-2082] Mim 2082 add backticks quotemarks

- package-lock.json
- package.json
- src/main/resources/react4xp/_entries/Breadcrumb.tsx
[Link to ticket: MIM-2040](https://statistics-norway.atlassian.net/browse/MIM-2040)
> [MIM-2040] Update breadcrumb component mobileCompressedView 

- src/main/resources/lib/ssb/rss/news.ts
- src/main/resources/lib/ssb/statreg/statistics.ts
- src/main/resources/services/rssNews/rssNews.ts
[Link to ticket: MIM-2141](https://statistics-norway.atlassian.net/browse/MIM-2141)
> [MIM-2141] Mim 2141 rss news 90 days

- src/main/resources/site/parts/pictureCardLinks/pictureCardLinks.ts
[Link to ticket: MIM-1964](https://statistics-norway.atlassian.net/browse/MIM-1964)
> [MIM-1964] MIM-1964:Fixed imageUrl if only two pictureCard

- src/main/resources/assets/styles/_statbankBox.scss
- src/main/resources/react4xp/_entries/StatbankBox.tsx
[Link to ticket: MIM-2122](https://statistics-norway.atlassian.net/browse/MIM-2122)
> [MIM-2122] Removal of h3 from statbankBox part

- src/main/resources/react4xp/_entries/PifCalculator.tsx
MIM-2162
[Link to ticket: MIM-2162](https://statistics-norway.atlassian.net/browse/MIM-2162)
> [MIM-2162] Fix average year validation for Pif Calculator

- src/main/resources/react4xp/_entries/PifCalculator.tsx
Fix average year validation for Pif Calculator
MIM-2162
> Deploy master to develop

- src/main/resources/react4xp/table/Table.tsx
[Link to ticket: MIM-1947](https://statistics-norway.atlassian.net/browse/MIM-1947)
> [MIM-1947] Mim 1947 fix file name table export

- src/main/resources/lib/types/partTypes/keyFigure.ts
- src/main/resources/site/content-types/keyFigure/keyFigure.xml
- src/main/resources/site/parts/keyFigure/keyFigure.ts
[Link to ticket: MIM-2092](https://statistics-norway.atlassian.net/browse/MIM-2092)
[🗄️ Link to branch admin interface!](https://ssbno-mim-2092.intern.test.ssb.no/admin)
[📰 Front page can be found here!](https://ssbno-mim-2092.intern.test.ssb.no/)
> [MIM-2092] Mim 2092 manual date input for key figures

- src/main/resources/lib/ssb/utils/utils.ts
- src/main/resources/lib/types/partTypes/pictureCardLinks.ts
- src/main/resources/react4xp/_entries/PictureCardLinks.tsx
- src/main/resources/site/mixins/linkTarget/linkTarget.xml
- src/main/resources/site/parts/pictureCardLinks/pictureCardLinks.ts
- src/main/resources/site/parts/pictureCardLinks/pictureCardLinks.xml
- src/main/resources/site/parts/profiledBox/profiledBox.ts
- src/main/resources/site/parts/profiledBox/profiledBox.xml
[Link to ticket: MIM-2026](https://statistics-norway.atlassian.net/browse/MIM-2026)
[🗄️ Link to branch admin interface!](https://ssbno-mim-2026.intern.test.ssb.no/admin)
[📰 Front page can be found here!](https://ssbno-mim-2026.intern.test.ssb.no/)
> [MIM-2026] Mim 2026 picture card links url

- src/main/resources/site/pages/default/default.html
[Link to ticket: MIM-2113](https://statistics-norway.atlassian.net/browse/MIM-2113)
> [MIM-2113] Favicon - sizes=32x32 added to ico

- package-lock.json
- package.json
MIM-2037
[🗄️ Link to branch admin interface!](https://ssbno-mim-2037.intern.test.ssb.no/admin)
[📰 Front page can be found here!](https://ssbno-mim-2037.intern.test.ssb.no/)
> [MIM-2037] Bump @statisticsnorway/ssb-component-library from 2.4.3 to 2.4.4

- src/main/resources/lib/ssb/parts/keyFigure.ts
- src/main/resources/lib/types/partTypes/keyFigure.ts
- src/main/resources/site/content-types/keyFigure/keyFigure.xml
- src/main/resources/site/parts/keyFigure/keyFigure.ts
[Link to ticket: MIM-2092](https://statistics-norway.atlassian.net/browse/MIM-2092)
> [MIM-2092] ManualDate render fixes for KeyFigures

- src/main/resources/lib/ssb/parts/keyFigure.ts
- src/main/resources/lib/types/partTypes/keyFigure.ts
- src/main/resources/site/content-types/keyFigure/keyFigure.xml
- src/main/resources/site/parts/keyFigure/keyFigure.ts
[Link to ticket: MIM-2092](https://statistics-norway.atlassian.net/browse/MIM-2092)
> [MIM-2092] MIM-2092-keyFigures, manual date fixes 

- package-lock.json
- package.json
- src/main/resources/site/pages/default/default.ts
[Link to ticket: MIM-2150](https://statistics-norway.atlassian.net/browse/MIM-2150)
> [MIM-2150] Mim 2150 new version compoment library

- src/main/resources/site/i18n/phrases.properties
- src/main/resources/site/i18n/phrases_en.properties
- src/main/resources/site/i18n/phrases_nn.properties
- src/main/resources/site/parts/relatedStatistics/relatedStatistics.ts
[Link to ticket: MIM-2149](https://statistics-norway.atlassian.net/browse/MIM-2149)
> [MIM-2149] MIM-2149:Changed phrase related statistics

- build.gradle
- src/main/resources/lib/ssb/repo/job.ts
MIM-2224
[Link to ticket: MIM-2224](https://statistics-norway.atlassian.net/browse/MIM-2224)
> [MIM-2224] Downgrade lib-cron to previous version

- package-lock.json
- package.json
- src/main/resources/assets/styles/_statisticDescription.scss
- src/main/resources/site/parts/statisticDescription/statisticDescription.ts
[Link to ticket: MIM-2210](https://statistics-norway.atlassian.net/browse/MIM-2210)
> [MIM-2210] Mim 2210 tweaks statistics

- src/main/resources/site/i18n/phrases_en.properties
New articles, analysis og publications er rettet ved at ordet "og" er byttet ut med "and".
> engelsk frase rettet opp i linje 433

- src/main/resources/admin/tools/dashboard/dashboard.es6
MIM-2222
[Link to ticket: MIM-2222](https://statistics-norway.atlassian.net/browse/MIM-2222)
> [MIM-2222] Change startegRapportUrl fallback url to new statreg rapport url

- src/main/resources/react4xp/_entries/StatisticFigures.tsx
[Link to ticket: MIM-2254](https://statistics-norway.atlassian.net/browse/MIM-2254)
> [MIM-2254] fixed click area on statbank link

- src/main/resources/lib/ssb/utils/markdownUtils.ts
- src/main/resources/services/getMarkdownNodes/getMarkdownNodes.ts
- src/main/resources/services/getMarkdownNodes/getMarkdownNodes.xml
- src/main/resources/services/postMarkdown/postMarkdown.ts
Created a service to get the markdown nodes, which can be used in a custom selector later.
[Link to ticket: MIM-2232](https://statistics-norway.atlassian.net/browse/MIM-2232)
> [MIM-2232] Mim 2232 create service to get markdown nodes

- src/main/resources/site/parts/statisticDescription/statisticDescription.tsx
[Link to ticket: MIM-2270](https://statistics-norway.atlassian.net/browse/MIM-2270)
> [MIM-2270] fix rendering macros in statisticsDescription

- src/main/resources/assets/styles/_calculator.scss
- src/main/resources/react4xp/_entries/BkibolCalculator.tsx
- src/main/resources/react4xp/_entries/KpiCalculator.tsx
- src/main/resources/react4xp/_entries/PifCalculator.tsx
- src/main/resources/react4xp/calculator/CalculatorLayout.tsx
- src/main/resources/site/parts/husleieCalculator/husleieCalculator.tsx
[Link to ticket: MIM-2274](https://statistics-norway.atlassian.net/browse/MIM-2274)
> [MIM-2274] MIM-2274-calculator-content

- src/main/resources/site/content-types/upcomingRelease/upcomingRelease.xml
- src/main/resources/site/i18n/phrases.properties
- src/main/resources/site/i18n/phrases_en.properties
- src/main/resources/site/i18n/phrases_nn.properties
[Link to ticket: MIM-2220](https://statistics-norway.atlassian.net/browse/MIM-2220)
> [MIM-2220] Innhold til publiseringskalender

- src/main/resources/lib/ssb/cron/task.ts
- src/main/resources/lib/ssb/dataset/dataset.ts
[Link to ticket: MIM-2278](https://statistics-norway.atlassian.net/browse/MIM-2278)
[🗄️ Link to branch admin interface!](https://ssbno-mim-2278.intern.test.ssb.no/admin)
[📰 Front page can be found here!](https://ssbno-mim-2278.intern.test.ssb.no/)
> [MIM-2278] Mim 2278 more job logging and retry logic for refreshQueriesAsync

- src/main/resources/lib/ssb/parts/keyFigure.ts
- src/main/resources/lib/types/partTypes/keyFigure.ts
- src/main/resources/site/parts/keyFigure/keyFigure.ts
[Link to ticket: MIM-2182](https://statistics-norway.atlassian.net/browse/MIM-2182)
> [MIM-2182] Mim 2182 keyfigures en phrase fix

- src/main/resources/site/parts/statisticContact/statisticContact.xml
- src/main/resources/site/parts/statisticDescription/statisticDescription.xml
- src/main/resources/site/parts/statisticFigures/statisticFigures.xml
- src/main/resources/site/parts/statisticHeader/statisticHeader.xml
[Link to ticket: MIM-2271](https://statistics-norway.atlassian.net/browse/MIM-2271)
> [MIM-2271] Removed prototype from new statistics part names

- package-lock.json
- package.json
Reverts statisticsnorway/mimir#3113 because of build failure
> Revert "Bump eslint-config-prettier from 9.1.0 to 10.0.1"

- src/main/resources/index.d.ts
- src/main/resources/react4xp/_entries/CookieBanner.tsx
- src/main/resources/site/pages/default/default.html
[Link to ticket: MIM-2299](https://statistics-norway.atlassian.net/browse/MIM-2299)
> [MIM-2299] Adding gtag to cookiebanner 

- src/main/resources/lib/types/cookieBanner.ts
- src/main/resources/react4xp/_entries/CookieBanner.tsx
- src/main/resources/site/i18n/phrases.properties
- src/main/resources/site/i18n/phrases_en.properties
- src/main/resources/site/i18n/phrases_nn.properties
- src/main/resources/site/pages/default/default.ts
[Link to ticket: MIM-2299](https://statistics-norway.atlassian.net/browse/MIM-2299)
> [MIM-2299] Fixed translations for cookieBanner

- src/main/resources/site/parts/timeline/timeline.ts
MIM-2292
[Link to ticket: MIM-2292](https://statistics-norway.atlassian.net/browse/MIM-2292)
> [MIM-2292] Fix links for Expansion Box in Timeline part

- src/main/resources/lib/ssb/cache/partCache.ts
- src/main/resources/site/macros/simpleStatbank/simpleStatbank.ts
- src/main/resources/site/parts/simpleStatbank/simpleStatbank.ts
[Link to ticket: MIM-2329](https://statistics-norway.atlassian.net/browse/MIM-2329)
> [MIM-2329] fix: Add part cache to Simple Statbank

- src/main/resources/assets/styles/_timeline.scss
- src/main/resources/site/parts/timeline/timeline.tsx
- Adjust line-height to 1.75 rem for text
- Fix headers for all variations/options for the Timeline events
[Link to ticket: MIM-2241](https://statistics-norway.atlassian.net/browse/MIM-2241)
> [MIM-2241] style: Adjustments to Timeline part component styling

- src/main/resources/assets/styles/_cookieBanner.scss
- src/main/resources/react4xp/_entries/CookieBanner.tsx
- src/main/resources/site/i18n/phrases_en.properties
- src/main/resources/site/pages/default/default.html
[Link to ticket: MIM-2299](https://statistics-norway.atlassian.net/browse/MIM-2299)
> [MIM-2299] Mim 2299 cookie banner

- .github/workflows/jira_issue_title.yaml
> ci: Modify jira issue title workflow [MIM-2227]

- .github/dependabot.yml
[Link to ticket: MIM-2227](https://statistics-norway.atlassian.net/browse/MIM-2227)
> style: [MIM-2227] Add prefix for dependabot PR

- src/main/resources/lib/types/partTypes/article.ts
- src/main/resources/site/parts/article/article.ts
- src/main/resources/site/parts/article/article.tsx
---
fix: A bug fix
---
- If your branch name matches the Jira pattern (e.g., …
> refactor:Updates time element to render ISO format [MIM-2181]

- .github/workflows/deploy_nais.yaml
Update `deploy_nais.yaml` to reflect main branch rename in `ssbno-xp-docker` repository.
> ci: Update deploy_nais.yaml ref from master -> main

- src/main/resources/services/solrUpdater/solrUpdater.ts
- Adds logging with yesterday's date and hit count for content
- Move yesterday const in get function and use camel case for modifiedTime in query
- Use dateTime instead of date for more accurate finds. The incremental solr crawler runs every 10 minutes.
Link to ticket: MIM-2341
> fix: Bug fixes for Solr updater service [MIM-2341]

- src/main/resources/react4xp/_entries/CookieBanner.tsx
Prevent infinite 500 ms polling of the setCookieConsent endpoint by tracking failures and clearing the interval after 3 consecutive non-200 responses.
Stops the endless 500 ms fetch loop on https://ssb-xp7p-admin.enonic.cloud/ when setCookieConsent is unreachable.
Fixes the issue without altering any existing consent-banner behavior.
Link to ticket: MIM-2350
> fix:Stop setCookieConsent polling after 3 failures [MIM-2350]

- .github/workflows/create-release-pr.yaml
Adding debugging
Link to ticket: MIM-2227
> refactor: adding debugging to GitHub action [MIM-2227]

- .github/workflows/create-release-pr.yaml
---
fix: A bug fix
---
- If your branch name matches the Jira pattern (e.g., …
> build: tweak release workflow [MIM-2227]

- .github/workflows/deploy_to_prod.yaml
[Link to ticket: MIM-2227](https://statistics-norway.atlassian.net/browse/MIM-2227)
> ci: [MIM-2227] Modify prod deploy action to use generated changelog.md

- .github/pull_request_template.md
- .github/workflows/create-release-pr.yaml
- release-please-config.json
---
fix: A bug fix
---
- If your branch name matches the Jira pattern (e.g., …
> build: Release please looking for wrong tag [MIM-2227]

- src/main/resources/lib/ssb/utils/utils.ts
- src/main/resources/site/parts/profiledBox/profiledBox.ts
> fix: Fix sub title conditions for Profiled Box part [MIM-2379]

- webpack.config.react4xp.js
> refactor: split dependencies out from vendor chunk [MIM-2378]

- src/main/resources/lib/ssb/utils/dateUtils.ts
- src/main/resources/site/pages/default/default.ts
- src/main/resources/site/parts/article/article.ts
---
fix: A bug fix
chore: Releasing new version
---
- If your branch name matches …
> fix: set date as iso in article modified date [MIM-2336]

- .github/workflows/deploy_to_qa.yaml
---
fix: A bug fix
chore: Releasing new version
---
- If your branch name matches …
> fix: remove commit message from slack on mabl fail
