statisticsnorway/mimir

src/main/resources/site/pages/default/default.html
src/main/resources/site/parts/banner/banner.html
src/main/resources/site/processors/searchableText.es6
src/main/resources/site/site.xml

remove searchable text from all regions and add it to banner and text parts only. Since we're not controlling text parts I had to do it in postprocessing instead.

MIMIR-321 searchable text

---

src/main/resources/lib/klass/municipalities.ts
src/main/resources/site/parts/banner/banner.es6
src/main/resources/site/parts/banner/banner.html

Våler og Herøy henter nå data fra gamle kommunenr, og tittelen i banneren viser nå ikke dobbelt opp med fylkesnavn.

Mimir 483 fikse duplikate kommuner klassliste

---

src/main/resources/site/parts/highchart/highchart.es6

- [MIMIR-452](https://jira.ssb.no/browse/MIMIR-452) : Highchart content-type supports a htmlTable input already - providing it with a correct config for rendering properly.

MIMIR-452 : highchart from static table

---

docs/StatReg.md

- Contacts are fetched from statreg and stored under `no.ssb.statreg` at `/contacts`. 
- Provides `getContactsFromRepo` utility interface that can be used to pick contacts from the mount point (f.eks. for use in an XP Part or customSelector)
- Provides an easy mechanism to mount similar content in the future (f.eks. `/publications` or `/statistics`) using the `configureNode(<mount-point-name>, <fetchFunction>)` interface. 
- In the simplest of scenarios (where the whole content is mounted at the topmost level in the `no.ssb.statreg` repo), all that is required is an additional line for the fetcher function. The following snippet shows saving publications, f.eks. -- 
```javascript
import { fetchContacts } from './statreg/contacts'
import { fetchStatistics } from './statreg/statistics' …
```

MIMIR-487 Fetch contacts from Statistikkregisteret

---

package-lock.json
package.json

Fixed in https://github.com/statisticsnorway/ssb-component-library/pull/203

Accordions and Glossary should always keep content in DOM

---

src/main/resources/lib/highcharts/config.es6
src/main/resources/site/parts/highchart/highchart.es6

- Move y-axis title outside of the labels-zone but at the same offset
- No clean solution for the x-axis, though -- for now positioning the title at the right end, but leaving it to highcharts to render it below the labels.
- Works similar on all types of charts with axes
---

MIMIR-617 : Fix axes title overlapping with labels

---

src/main/resources/lib/highcharts/config.es6
src/main/resources/site/content-types/highchart/highchart.ts
src/main/resources/site/content-types/highchart/highchart.xml

Allow specifying aspect ratio of the chart (expressed as percentage of height wrt. width of the chart)
| % specified | Aspect Ratio |
|-------------|--------------|
| 100 | 1:1 |
|75 | 4:3 (_default_) |
| 62 | Golden Ratio |
| 56 | 16:9 |
| 162 | Golden Ratio (vertical) |
| 0 | Highcharts default |
---

MIMIR-615 : Highcharts Aspect Ratio

---

src/main/resources/lib/highcharts/config.es6
src/main/resources/site/content-types/highchart/highchart.ts
src/main/resources/site/content-types/highchart/highchart.xml

- Add option to show stacked totals (_highchart_ content-type)
- If stacking mode is 'normal' (cumulative) and show stacked totals is enabled, then display the total on top of (or by the side) of the stacking
- Works for _line_, _bar_, _column_, _area_ and _pyramid_ chart types
---

MIMIR-618 : show stacked totals

---

src/main/resources/lib/ssb/menu.ts
src/main/resources/site/pages/default/default.es6

If a current content has parts of a menuitems "manual" url, make the menuitem active
- Add a check of current content path
- Extend cache name with url path, so that each path has its own cached menu
MIMIR-640

MIMIR-640: Make menuitem active

---

src/main/resources/assets/styles/_contacts.scss
src/main/resources/site/layouts/columns/columns.html
src/main/resources/site/layouts/topic/topic.html
src/main/resources/site/pages/default/default.html
src/main/resources/site/parts/contact/contact.html

- Nests titles for one and two column layouts in container, row, and column.
- Breadcrumbs, alerts, and titles are also nested in a container, row and column along with a few minor tweaks to each element.
- Tweaks h2 title for containers with a green border on top and adds another for plain pages.
- CSS adjustments for the contacts, mobile version.
These changes should fix the indent for titles (including Data til Forskning) and content in articles (contacts) in any resolution.

Mimir 679 indents titles content

---

package.json
src/main/resources/site/parts/relatedFactPage/relatedFactPage.jsx

Use new version of SSB Component Library ([v2.0.29](https://github.com/statisticsnorway/ssb-component-library/releases/tag/2.0.29)) with fix for contrast bg in picture cards

MIMIR-491 : Contrast bg for picture cards

---

src/main/resources/lib/repo/statreg/statistics.ts
src/main/resources/lib/ssb/statreg/common.ts
src/main/resources/lib/ssb/statreg/config.ts
src/main/resources/lib/ssb/statreg/index.ts
src/main/resources/lib/ssb/statreg/types.ts

- use new statreg endpoint **GET** `{statreg}/statistics` (ref: [documentation](https://wiki.ssb.no/display/NYP/StatReg%3A+Suggestions+for+new+endpoints))
- refractor code to support both xml and json response from statreg api
----
- **OBS**: setting a huge conn- and readTimeout (`500s`) as the endpoint regularly failed to fetch from utv/test. 
- this value will be updated once it is confirmed to work with meaningful values for the timeouts (`30s`)

MIMIR-703 : Use new statreg endpoint for statistics

---

package-lock.json
src/main/resources/assets/styles/_statistics.scss
src/main/resources/site/content-types/articleArchive/articleArchive.ts
src/main/resources/site/i18n/phrases.properties
src/main/resources/site/i18n/phrases_en.properties
src/main/resources/site/i18n/phrases_no.properties
src/main/resources/site/parts/statistics/statistics.es6
src/main/resources/site/parts/statistics/statistics.html

- Displays statistics name, previous release and next release dates from Statreg.
- Shows default display name and generic text for dates if no statistics are selected in the content selector.
- Text that can be translated has been added to phrases. Those phrases are used in the statistics part.

Mimir 666: Display data from statreg for Statistics pages

---

src/main/resources/site/content-types/articleArchive/articleArchive.ts
src/main/resources/site/content-types/articleArchive/articleArchive.xml

- Replaces the previously 'URL' text field with a html area renamed to 'Fritekst'.
- Moves the free text field higher, above ISSN, to follow the flow of the visual layout.

Mimir 536 article archive field adjustment

---

.drone.yml

Testing Mabl integration with Drone, building on QA deploy run

Adds Mabl end-to-end testing as part of QA deploy pipeline

---

src/main/resources/lib/highcharts/config.es6

Set `reversed` to `false` for x-axis categories

MIMIR-659: correct order of x-axis categories

---

src/main/resources/assets/styles/_omStatistikken.scss
src/main/resources/assets/styles/_relatedArticles.scss
src/main/resources/assets/styles/_statbankBox.scss
src/main/resources/assets/styles/_table.scss
src/main/resources/assets/styles/main.scss
src/main/resources/site/parts/omStatistikken/omStatistikken.html
src/main/resources/site/parts/statbankBox/statbankBox.html

- Fixes indentation for parts: omStatistikken, relatedArticles, statBankBox, and table.
- Nests some parts in rows and columns which fixes the indentation on desktop, whilst a padding/margin 0 for all parts fixes the issue for mobile.

MIMIR-742 indentation statistics page

---

package-lock.json
package.json
src/main/resources/assets/js/tableExport.js
src/main/resources/react4xp/_entries/Table.jsx

- Uses the copy of the tableExport plugin source code from ssbno 4.7. instead of the npm package.

Mimir 719 fixes table download csv PART 2

---

src/main/resources/assets/styles/_attachmentTablesFigures.scss
src/main/resources/site/parts/attachmentTablesFigures/attachmentTablesFigures.es6

- Adds a set width for sub header so that header text for attachment tables and figures in the accordion will start on the same line.
- Adds a counter for table- and figureIndex in the attachmentTablesFigures part controller, number is displayed on the accordion sub header text.

Mimir 74 sub header tables figures accordion fixes

---

src/main/resources/site/content-types/article/article.ts
src/main/resources/site/content-types/article/article.xml

- Moves the forms in article content type in the correct order.
- Puts the remaining fields into field sets for consistency's sake.

Mimir 110 article forms order

---

src/main/resources/assets/styles/_article.scss
src/main/resources/assets/styles/_associatedArticleArchives.scss
src/main/resources/assets/styles/_associatedStatistics.scss
src/main/resources/assets/styles/main.scss
src/main/resources/site/i18n/phrases.properties
src/main/resources/site/i18n/phrases_en.properties
src/main/resources/site/i18n/phrases_no.properties
src/main/resources/site/parts/article/article.es6
src/main/resources/site/parts/article/article.html
src/main/resources/site/parts/associatedArticleArchives/associatedArticleArchives.es6
src/main/resources/site/parts/associatedArticleArchives/associatedArticleArchives.html
src/main/resources/site/parts/associatedArticleArchives/associatedArticleArchives.xml
src/main/resources/site/parts/associatedStatistics/associatedStatistics.es6
src/main/resources/site/parts/associatedStatistics/associatedStatistics.html
src/main/resources/site/parts/associatedStatistics/associatedStatistics.xml

- Moves associated statistics and article archives code from article part to their new respective parts; associatedStatistics and associatedArticleArchives.
- Removes divider and other unnecessary code (imports previously used on code that is no longer there) from article part.
- Uses Links react component for the associated statistics and article archive links.

Mimir 107 associated statistics and article archives

---

src/main/resources/react4xp/_entries/KeyFigure.jsx

- Adds a conditional check for keyFigures addPreviewInfo to return alert variant warning when the number prop in keyFigures is empty.

MIMIR-145 fix keyfigures unpublished alert

---

src/main/resources/lib/language.es6

- Displays only the English alternative language option link for the fallback menu

MIMIR-316 fallback menu altLanguage link

---

.github/workflows/action.yml

Added types: opened to action.yml. This should fix multiple assignees to the same PR.

Auto-assign should now only run when PR are opened

---

src/main/resources/site/pages/default/default.es6
src/main/resources/site/pages/default/default.html

We can not use the SEO app alternative, as the statbank and other frames would get the wrong path.
MIMIR-785

Adds canonical url to all pages.

---

src/main/resources/lib/ssb/error/error.ts

Also removed unused interface Exception.
Also renamed Error to ErrorInterface, as it conflicted with global object Error.

Changed accepted type to built-in object type Error

---

src/main/resources/lib/ssb/parts/publicationArchive.ts

Different dateformat on statistics and articles made the sorting wrong

MIMIR-965:Fixed sorting

---

.github/workflows/mabl_test.yml
.github/workflows/merge_mabl_feature_branch.yml

All Mabl workflows in github is failing because of being locked to an
old node.js version through the docker image tag.
This change updates the tag from "10.18-jessie" to the more generic
"lts".

Update container version running node.js

---

.github/workflows/deploy_to_qa.yaml
.github/workflows/deploy_to_test.yaml

Github Actions is a recommended tool for the CI/CD prosess for Enonic XP.
This change creates two Workflows for Github Actions, one to build and deploy to the test environment when a new PR is opened; the other to build and deploy to QA environment when a change is pushed to the branch 'master'.
int.ref: [MIMIR-1227]
[MIMIR-1227]: https://statistics-norway.atlassian.net/browse/MIMIR-1227?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Test Github Actions as CI/CD tool

---

.github/workflows/deploy_to_qa.yaml
.github/workflows/deploy_to_test.yaml

We want to run Mabl tests on the published versions. These changes has been done to achive this:
* Add job to run Mabl test
* Move XP deploy URLs to github secrets
* Force Github Action to react to push on this branch, to allow for testing
* Fix typo in job name (an error from a previous PR)
* Update test cert and key to allign the naming convention for the Github action secrets

Add mabl tests to github action

---

.github/workflows/deploy_to_prod.yaml
.github/workflows/deploy_to_qa.yaml
.github/workflows/deploy_to_test.yaml
.github/workflows/manual_deploy_to_prod.yaml
.github/workflows/manual_deploy_to_test.yml

We want to enable Github actions to replace Drone as the tool for building and deploying new code.
This is made possible with two automatic workflows, one that triggers on creating Pull Request and deploys to the test environment, and one that triggers on merge to the main branch and deploys to the QA environment. Both these workflows will upload the built artifacts when successful.
In addition we have created to workflows that has to be manually triggered, and needs the run number for a previously successful run of one of the two automatic workflows as input. These workflows download the previously built artifacts and deploys them, to the test or production environments respectively.
All workflows report results to a Slack channel.

Mimir 1227 updates and manual deploy workflow

---

package-lock.json

Downgrade to match package.json The reason is the newer version prints lots of warnings during build

Downgrade autoprefixer

---

src/main/resources/assets/js/app/highchart.es6
src/main/resources/site/parts/nameSearch/nameSearch.jsx

fixes the error - where nynorsk pages still have decimalpoint = ' . ' and where the text is in english 
this will set the default highcharts language to nb / nn and use the default higcharts language when lang === en (witch is english)

nn fix( !=='en')

---

src/main/resources/site/layouts/triple/triple.es6

Resolved the Thymeleaf rendering error: "Exception evaluating OGNL expression: 'centerRegion.components'" (found in "mimir:/site/layouts/triple/triple.html" - line 11, col 12). Implemented a check for null or undefined variables before template parsing. Added a safeguard to assign empty arrays to variables if they are null or undefined, preventing Thymeleaf from throwing errors when a region is empty at render time.

Fix Thymeleaf Rendering Error by Handling Undefined Variables

---

src/main/resources/services/contacts/contacts.es6

Resolved issue preventing addition of new contacts after one is deleted.
When a contact is removed, it's now replaced with a placeholder row labeled "(slettet kontakt)". This ensures consistent behavior and prevents previous bugs. The placeholder can be safely deleted without affecting the addition of new contacts.

mimir-1877-Layout-i- fragmenter-gir-feil

---

src/main/resources/lib/ssb/dataset/calculator.ts
src/main/resources/react4xp/dashboard/containers/DashboardTools/index.jsx
src/main/resources/site/error/error.html
src/main/resources/site/macros/headerLink/headerLink.ts
src/main/resources/site/pages/default/default.html
src/main/resources/site/pages/default/default.ts
src/main/resources/site/parts/accordion/accordion.ts
src/main/resources/site/parts/button/button.ts
src/main/resources/site/parts/kpiCalculator/kpiCalculator.ts
src/main/resources/site/parts/links/links.ts
src/main/resources/site/parts/publicationArchive/publicationArchive.jsx

Fixed sonarcloud issues tha require minimal changes and should not touch logic/refactoring of code. Some issues are done in separate tasks later.
Link: https://sonarcloud.io/project/issues?resolved=false&types=BUG&id=statisticsnorway_mimir&open=AYMMS1dSbIx-Cxvq32om
Sonarcloud bugs not fixed:
* Highcharts code are done separately
* RefreshStatisticsForm is fixed separately since this will touch logic

Fixed easy sonarcloud bugs

---

src/main/resources/react4xp/_entries/relatedImageBox.jsx

Fjerne ubruk react komponent. Den importere noe som ikke fantes fra komponentbiblioteket som ga warnings i bygg loggene.

Remove unused entry

---

src/main/resources/assets/styles/_videoEmbed.scss
src/main/resources/assets/styles/main.scss
src/main/resources/index.d.ts
src/main/resources/site/i18n/phrases.properties
src/main/resources/site/i18n/phrases_en.properties
src/main/resources/site/i18n/phrases_nn.properties
src/main/resources/site/parts/videoEmbed/videoEmbed.ts
src/main/resources/site/parts/videoEmbed/videoEmbed.xml

[Link to ticket: MIM-1356](https://statistics-norway.atlassian.net/browse/MIM-1356)

[MIM-1356] Add part for video embed of vimeo and youtube

---

src/main/resources/lib/ssb/cron/cron.ts

Flyttet de fleste cron jobbene inni isMaster istedenfor å kjøre runOnlyOnMaster på hver callback. De som skal kjøre på hver node (clear cache) er flytta uttafor den. 
Det at libScheduleTest slettet også lagde en schedule gjorde at det ble mye kluss og asynkhet når dette skjedde på alle noder. 
[Link to ticket: MIM-1707](https://statistics-norway.atlassian.net/browse/MIM-1707)

[MIM-1707] Wrap most cron jobs in isMaster so no duplicate work is done

---

src/main/resources/assets/js/app/highchart.es6

I changed the original if statement to also enable markers for series.data that only contain one non-null data point. Now, if a series has only one data point, that point will be marked, and the user will not need to hover over it to see it.
[Link to ticket: MIM-1610](https://statistics-norway.atlassian.net/browse/MIM-1610)

[MIM-1610] MIM-1610-fixed lacking visual for single point series

---

gradle.properties
src/main/resources/lib/ssb/cron/cron.ts

[Link to ticket: MIM-1707](https://statistics-norway.atlassian.net/browse/MIM-1707)

[MIM-1735] Hotfix revert mim 1707 wrap cron is master

---

src/main/resources/lib/ssb/utils/variantUtils.ts
src/main/resources/services/upcomingReleases/upcomingReleases.ts
src/main/resources/site/parts/upcomingReleases/upcomingReleases.ts

* All publications are sorted in react-component. I have therefore removed all sorting until then
* Improved filter to only filter releases once (instead of filter all release for each day, potentially 700 instead of 1)
* Only filter by start date once (before it first filtered from now, and then filtered from a given start date)
[Link to ticket: MIM-1743](https://statistics-norway.atlassian.net/browse/MIM-1743)

[MIM-1743] Refactoring upcoming publications removing unnecessary filter and sorting

---

src/main/resources/site/parts/nameSearch/nameSearch.jsx

funker førstegang man går in på url med #ancorpoint, men fungerer ikke på refresh i chrome, (dette er ett chrome issue som vi ikke trenger å tenke på atm)
ser ut til å fungere perfekt på safari 
[Link to ticket: MIM-1712](https://statistics-norway.atlassian.net/browse/MIM-1712)

[MIM-1712] fix

---

src/main/resources/react4xp/_entries/Footer.jsx

In footer there was an wave-error on english page due to space in an id. The problem was only visible on english page where one of the sub titles had two spaces.

Fixed broken aria-labelledby in footer (only error in english)

---

package-lock.json
package.json
src/main/resources/react4xp/_entries/Search.jsx

404 siden skal kanskje byttes ut i fremtiden, men dette fisker ivertfall søket for nå.
Error sider støtter ikke pageContributions i render response, som er noe React4xp trenger for å hydrere siden. Dette gjør at vi ikke kan bruke event listeners o.l. via react. 
[Link to ticket: MIM-1787](https://statistics-norway.atlassian.net/browse/MIM-1787)

[MIM-1787] Fix search in 404 page. Cant hydrate so use good ol html

---

package.json

This section is only relevant to tell consumers of the npm package what engines your package depends on. Since we don't release any npm it is neither updated by us or relevant to any consumers. Hence removing it.

Removed engines section i package.json

---

src/main/resources/site/parts/highmap/Highmap.jsx

Det er ekstremt mange steder det blir definert tekst stiler for deler av grafene. Det bør bli ryddet opp i når vi går over til react-highchart og standardiserer config mellom highchart og highmap.

[MIM-1756] MAke highmap use open sans font

---

src/main/resources/site/parts/highchart/highchart.ts
src/main/resources/site/parts/highmap/highmap.ts

[Link to ticket: MIM-1747](https://statistics-norway.atlassian.net/browse/MIM-1747)

[MIM-1747] Make highmap show in edit mode

---

src/main/resources/lib/ssb/parts/highcharts/graph/config.ts
src/main/resources/site/content-types/highchart/highchart.xml

Because highcharts legend does not support margin-right, width is set to 75% to avoid most conflicts with download button.
[Link to ticket: MIM-1732](https://statistics-norway.atlassian.net/browse/MIM-1732)

[MIM-1732] added setting for top legend on highcharts

---

src/main/resources/lib/ssb/parts/highcharts/highchartsGraphConfig.ts
src/main/resources/site/content-types/combinedGraph/combinedGraph.xml

[Link to ticket: MIM-1884](https://statistics-norway.atlassian.net/browse/MIM-1884)
The "Kombinert Graf" content type upgrades:
1. Graph Type Flexibility: Individual graph types can be assigned to each series, suitable for complex visualizations on both single and dual y-axes.
2. Y-Axis Customization: The item-set previously known as graphs is now yAxis, enabling axis-specific configurations including minimum and maximum values for better data scale representation.
3. Series Configuration: A new series item-set supports up to 10 customizable series, each with a designated title, graph type, and y-axis,

[MIM-1884] Graph type per serie for combinedGraph

---

.github/workflows/deploy_to_qa.yaml

In order to catch repo in deployments and automations in jira we need repo name to be reflected in env name for QA

Add mimir to env setting i github

---

src/main/resources/admin/tools/dashboard/dashboard.es6
src/main/resources/react4xp/dashboard/containers/DashboardTools/index.tsx

[Link to ticket: MIM-1910](https://statistics-norway.atlassian.net/browse/MIM-1910)

[MIM-1910] Updated dashboard links

---

package-lock.json
package.json
src/main/resources/lib/types/partTypes/attachmentTablesFigures.ts
src/main/resources/lib/types/partTypes/table.ts
src/main/resources/react4xp/_entries/AttachmentTablesFigures.tsx
src/main/resources/react4xp/table/Table.tsx

[Link to ticket: MIM-2045](https://statistics-norway.atlassian.net/browse/MIM-2045)

[MIM-2045] Mim 2045 bugfix mobile scroll attachment table

---

src/main/resources/assets/styles/_popup.scss
src/main/resources/react4xp/_entries/Popup.tsx

- Imported Buttons from SSB-CL (focus works)
- When scrolling up to the top of the page the small icon will turn to bigger small
- Used local-storage to remember open/close state across page urls
Changes requested by desk
[Link to ticket: MIM-2066](https://statistics-norway.atlassian.net/browse/MIM-2066)

[MIM-2066] Various Fixes

---

package-lock.json
package.json

- Resolves `Server-side Request Forgery (SSRF) in axios` from Snyk Vulnerability Report. Also mentioned by Dependabot in the Security Alerts: https://github.com/statisticsnorway/mimir/security/dependabot/59
MIM-2078

Bump axios from 1.6.0 to 1.7.7

---

package-lock.json
package.json

- Override all `glob` dependencies to the version `mimir` is using 
- Resolves [Missing Release of Resource after Effective Lifetime](https://security.snyk.io/vuln/SNYK-JS-INFLIGHT-6095116) caused by deprecated module `inflight` which was a requirement for older `glob` versions
MIM-2079

[MIM-2079] Bump glob from 10.4.1 to 11.0.0

---

src/main/resources/site/content-types/statistics/statistics.xml
src/main/resources/site/mixins/relatedArticles/relatedArticles.xml
src/main/resources/site/parts/relatedArticles/relatedArticles.ts

[Link to ticket: MIM-1825](https://statistics-norway.atlassian.net/browse/MIM-1825)

[MIM-1825] RelatedArticles Fix

---

src/main/resources/main.es6
src/main/resources/site/pages/default/default.html
src/main/resources/site/pages/default/default.ts

This is an image of the what the Schema of an article looks like in this PR
- dateModified works
- publisher has been added 
- pageMap functionality has been removed from default.ts (as no longer being used)

[MIM-2108] Mim-2108-dateModified-datePublished-fix

---

src/main/resources/site/pages/default/default.ts

Endringene gir nå riktig Schema-resultat, der det alltid legges til 00 for sekunder og Z for UTC-tidssone, likt datePublished

[MIM-2108] MIM-2108-dateModified-schema-fix

---

src/main/resources/lib/ssb/utils/calculatorUtils.ts
src/main/resources/lib/ssb/utils/customHooks/calculatorHooks.tsx
src/main/resources/react4xp/_entries/BpiCalculator.tsx
src/main/resources/react4xp/calculator/CalculatorLayout.tsx
src/main/resources/services/bpiCalculator/bpiCalculator.ts

- Adds space between amount and valute for results
- Fixes validation for invalid start- and end index
- - Move to calculatorUtils and implement in bpi calculator service
- Adds validation for year depending on region pick; most regions have data all the way back to 2005 and the remaining two are the only ones dating back to 1992
[Link to ticket: MIM-2157](https://statistics-norway.atlassian.net/browse/MIM-2157)

[MIM-2157] Mim 2157 bpi calculator adjustments

---

.github/workflows/deploy_to_test.yaml

Since `ENONIC_CERT` and `ENONIC_KEY` is shared by all deploys, we will have to use these new env variables during the migration process

Update cert and key for deploy to test; possibly a temp solution

---

src/main/resources/services/postMarkdown/postMarkdown.ts
src/main/resources/services/postMarkdown/postMarkdown.xml

The service provides an endpoint _postMarkdown_ that takes parameters:
- `displayName` 
- `markdown` : the raw content of a markdown file
The service then creates a node in the repo _no.ssb.pubmd_ with properties _displayName_ and _markdown_.
[Link to ticket: MIM-2232](https://statistics-norway.atlassian.net/browse/MIM-2232)

[MIM-2232] Created service to add markdown content in a node in repo no.ssb.pubmd

---

build.gradle
src/main/resources/index.d.ts
src/main/resources/lib/ssb/utils/markdownUtils.ts
src/main/resources/services/getMarkdownNodes/getMarkdownNodes.ts
src/main/resources/site/parts/markdown/markdown.ts
src/main/resources/site/parts/markdown/markdown.tsx
src/main/resources/site/parts/markdown/markdown.xml

Created part to display markdown content.
- The part definition includes a custom selector that lets users choose the desired markdown content to render (specifically, it lets you choose among the nodes returned by the service getMarkdownNodes).
- The controller then does the following: 
- Gets the raw markdown content from the chosen node.
- Converts the markdown to html using the render function from Enonics markdown library: https://github.com/enonic/lib-markdown
- Renders the react component (with the html from above as the only property). 
- For now, the React component just sanitizes the html and inserts it into a div. 
[Link to ticket: MIM-2232](https://statistics-norway.atlassian.net/browse/MIM-2232)

[MIM-2232] Mim 2232 create markdown part

---

src/main/resources/lib/ssb/cron/cron.ts

Make sure fallback schedule is on or later than 7:50 both summer and winter.

Fix fallback schedule for cron

---

src/main/resources/site/parts/markdown/markdown.ts
src/main/resources/site/parts/markdown/markdown.xml

**Currently:**
* It's only possible to render Markdown-content received through the postMarkdown-endpoint.
* Implementation: we have a Markdown part that can be configured by choosing a node from the repo *no.ssb.pubmd*. This repo stores the Markdown content received through the endpoint. 
**Desired feature:**
* When adding a Markdown part to a page, an alternative configuration of the part is to paste raw Markdown content. 
**Solution:**
* This PR adds an additional text area input in the part definition, where raw markdown can be pasted.
* The first input (choosing a node) has priority, while the second input (text area) is a fallback when the first input has no value. 
**Limitations:**
* Choosing only one of the inputs is not enforced on the user, i.e. the user is allowed to use both …

[MIM-2310] Support pasting raw markdown

---

src/main/resources/lib/ssb/utils/markdownUtils.ts
src/main/resources/site/parts/markdown/markdown.ts

Before this PR, the _markdown_ part rendered the markdown text found in the part component of the current context (using [getComponent](https://developer.enonic.com/docs/xp/stable/api/lib-portal#getcomponent) from Portal API). 
In this PR, the _markdown_ part first checks if there is a content of type _markdown_ in the current context (using [getContent](https://developer.enonic.com/docs/xp/stable/api/lib-portal#getcontent) from the Portal API). 
* If yes, it renders the markdown text in the content.
* If no, it renders the markdown text from the part component as before. 
This change makes it possible to define a template for the content type _markdown_ (the _markdown_ part should be included somewhere in the template). The same has been done for the content type _article_ before, which …

feat: add content rendering to markdown part [MIM-2345]

---

src/main/resources/lib/ssb/utils/imageUtils.ts
src/main/resources/lib/ssb/utils/utils.ts
src/main/resources/site/parts/articleArchive/articleArchive.ts
src/main/resources/site/parts/profiledBox/profiledBox.html
src/main/resources/site/parts/profiledBox/profiledBox.ts
src/main/resources/site/parts/profiledBox/profiledBox.xml
src/main/resources/site/parts/relatedArticles/relatedArticles.ts
src/main/resources/site/parts/relatedFactPage/relatedFactPage.ts

* Fetch XP Content data for Editorial Cards part
* Move reusable functions for generating subtitle, urls, and images to utils
* Refactor Editorial Cards, Related Articles, Related Fact Page and Article Archive parts; uses previously mentioned util functions
Link to ticket: MIM-2058
[🗄️ Link to branch admin interface!](https://ssbno-mim-2058.intern.test.ssb.no/admin)
[📰 Front page can be found here!](https://ssbno-mim-2058.intern.test.ssb.no/)

feat: Fetch XP Content data for Editorial Cards part [MIM-2058]

---

src/main/resources/lib/ssb/cron/eventLog.ts
src/main/resources/site/parts/banner/banner.tsx

- Use date-fns lib instead of manually subtracting the dates ourselves for delete expired event log logic
Link to ticket: MIM-2376

fix: Use date-fns lib instead of manually subtracting the dates ourselves for delete expired event log logic [MIM-2376]
